#+title: The main aspects of renewable energies

** What is renewable energy?
All energy sources that get naturally replenished on a human scale are
considered renewable. For instance, the energy that is produced from
the Sun is considered renewable because, on a human scale, it will
never cease to exist. Popular forms of renewable energy are wind, sea waves and
geothermal heat, although there are also emerging technologies.
It is important to note that not all renewable energies are also
green energies. Some of them do emit huge amount of greenhouse gases.

** Solar energy
Solar energy is the most popular form of renewable energy. Solar panels nowadays
are cheap, can be installed almost everywhere and don't require much maintenance aside
from dust cleaning. They don't have a great capacity factor (ie. the amount of time energy
is produced in a year's time) and for this reason it must be paired with another source
of energy in order to guarantee power at night and during winters, especially for
factories and other power-hungry appliances such as electric trains which cannot be
powered from batteries.

** Geothermal energy
The insides of the Earth are really hot, and this heat can be turned into electrical
energy. Unlike solar energy, geothermal has a high capacity factor (90%), for this
reason it could replace coal and other fossil fuels, provided that the territory can
accomodate such plants.

** Is nuclear power considered renewable?
There is currently a debate on whether or not the nuclear energy should
be considered renewable. Nuclear fission (or fusion, in the future) produce
heat, which is then used to turn water into steam which powers a steam turbine.
Unlike other forms of renewable energies, nuclear power requires fissible
material like uranium in order to function. For this reason, many does
not consider nuclear power a renewable energy source. However, it must be
noted that uranium is present at great quantities on the Earth, especially
in ocean waters where it can be extracted from relatively cheap. Uranium is
also very energy dense, meaning that small quantities of material can produce
a lot of energy, for this reason we wouldn't run out of uranium even if we
powered the entire Earth with nuclear power.
Since nuclear power does not produce CO2 or other gases, it is also considered
green by the European Union.
