#+title: Italo Svevo

** Italo Svevo
Italo Svevo era un sinonimo di Schmitz. Metà italiano e metà Svevo.
Lavora in banca. Non ha una carriera da letterato, è autodidatta.
Sposa Lidia Veneziani e lavora alla società di vernici del suo padre.

Scrive due romanzi che però non hanno successo.
Pubblica la coscienza di Zeno che ha un grande successo e risente delle teorie di Freud.
Il suo romanzo viene appoggiato da Eugenio Montale.

** La teoria di Freud
Freud è il primo a teorizzare l'inconscio. Nella nostra mente c'è una scatola nera e quando.
Secondo Freud, le cose emergono dall'inconscio grazie ai lapsus.
Per Freud la psiche si divide in tre parti: es, io, super io. I bambini nascono solo con l'es.
Se siamo più verso l'es cerchiamo il nostro piacere, mentre al contrario siamo persone estremamente
rigide. Prime di Freud si pensava che le malattie psicologiche andassero curate fisicamente.

** Una vita e Selenità
Il primo protagonista, Alfonso Nitti. Un giovane che lavora in banca ed è appassionato di letteratura.
Vorrebbe sposare la figlia del suo capo. Alla fine si suicida.

Nei suoi romanzi c'è sempre un protagonista inetto ed un antagonista che è l'opposto.
