#+title: Italo Svevo

** Italo Svevo
Italo Svevo si chiamava in realtà Schmitz. Metà italiano e metà Svevo.
Lavora in banca. Non ha una carriera da letterato, ed è un autodidatta.
Sposa Lidia Veneziani e lavora alla società di vernici del suo padre.

Scrive due romanzi che però non hanno successo.
Pubblica la coscienza di Zeno che ha un grande successo e risente delle teorie di Freud.
Il suo romanzo viene appoggiato da Eugenio Montale.

** La teoria di Freud
Freud è il primo a teorizzare l'inconscio. Nella nostra mente c'è una scatola nera e quando.
Secondo Freud, le cose emergono dall'inconscio grazie ai lapsus.
Per Freud la psiche si divide in tre parti: es, io, super io. I bambini nascono solo con l'es.
Se siamo più verso l'es cerchiamo il nostro piacere, mentre al contrario siamo persone estremamente
rigide. Prime di Freud si pensava che le malattie psicologiche andassero curate fisicamente.

** Una vita, la trama
Il primo protagonista, Alfonso Nitti. Un giovane che lavora in banca ed è appassionato di letteratura.
Vorrebbe sposare la figlia del suo capo, anche lei appassionata lettrice. Essendo incapace di farlo,
decide di scappare nel Paese in cui vive la madre malata, ed una volta morta vende tutti
i suoi beni.
Quando torna al lavoro viene declassato e nel frattempo Anna si è fidanzata con Macario,
che svolge il ruolo del rivale e rappresenta il suo opposto.
Alfonso ad un certo punto rifiuta la lotta con il suo opponente e si suicida.

Nei suoi romanzi c'è sempre un protagonista inetto ed un antagonista che è l'opposto.

** Una vita, lo stile
Il romanzo è in terza persona, il narratore è esterno ed esprime giudizi contrastanti rispetto
a quelli del protagonista. La storia però alcune volte viene raccontata dal punto di vista
di Alfonso, in modo che il lettore possa entrare nella psiche del protagonista.

Il testo quindi introduce una dimensione dello scavo dell'inconscio.

** Senilità
Senilità ripropone il tema dell'impiegato inetto di "Una vita", ma da un altro punto di vista.
Il protagonista è un letterato ma che non si oppone alla normalità borghese in nome di una
formazione umanistica, ed al contrario, si unisce.

C'è un conflitto interiore tra desiderio e repressione, o in modo Freudiano, fra principio
di piacere e principio di realtà.

** Senilità, la trama
Protagonista: Emilio Brentani, impiegato 35enne. Frequenta i circoli letterari ed è conosciuto
per aver scritto un romanzo. Vive con la sorella Amalia, che non si è mai sposata.

Il suo unico amico è Stefano Balli, uno scultore poco talentuoso ma fortunato con le donne.
Un giorno Emilio vuole imitarlo e crede di aver trovato qualcuno quando incontra la bella
Angiolina, che però vuole solo regali e denaro. Così tenta di lasciarla ma si rende conto
che non riesce a vivere senza la giovinezza della donna e torna insieme.

Angiolina però si è innamorata di Balli, per il quale posa come modella e anche la sorella
Amalia ha una cotta per lui. Amalia per dimenticare si droga ma si ammala di una gravissima
polmonite.

Emilio abbandona la sorella per un ultimo appuntamento con Angiolina, in cui la insulta
violentemente.

Alla fine si chiude definitivamente nella "senilità" da cui non era mai uscito.

Svevo ci sta parlando di protagonisti inetti che non si vogliono lasciar andare a nessuna passione
e piuttosto rinuncia a vivere. Siamo agli antipodi rispetto alla letteratura romantica di Foscolo.
Non vogliono sentire nè il peso nè i rischi delle passioni.

** Senilità, i personaggi
Ci sono due uomini e due donne, entrambi contrapposti tra loro. Amalia ed Emilio sono sconfitti
e frustrati, mentre Balli ed Angiolina sono spregiudicati e fortunati in amore.

Il narratore è in terza persona ed a volte interviene sminuendo i protagonisti.

** Senilità, il tema
La senilità è una metafora, nessuno dei personaggi è vecchio, piuttosto la senilità è una condizione
psicologica segnata dalla rinuncia ad ogni emozione.

Emilio potrebbe vincere la senilità se mettesse in discussione la sua vita normale e tranquilla,
ma essendo privo di coraggio non riesce. Cerca così di influenzare Angiolina, che rappresenta
l'amore e che vorrebbe possedere senza mai concedersi, come se fosse un oggetto.

** La coscienza di Zeno
Scritto nel 1923, dopo 25 anni dai precedenti. Ambientato a Trieste, come gli altri due romanzi.
Il protagonista è Zeno Cosini. Il romanzo si percorre per percorsi tematici. È un diario scritto per il
suo psicanalista.

Gioca sulla varietà dei significati del termine "coscienza" che può valere sia come "coscienza
morale" che come "consapevolezza".

Il romanzo è formato da 8 capitoli. La struttura non segue un ordine cronologico ma tematico,
affrontando questioni diverse. Si produce un flusso di memoria, come un tempo misto.

*** Temi:
- Prefazione
  Il dottor S. spiega che ha spinto Zeno a scrivere una storia della sua malattia;

- Preambolo
  L'anziano Zeno riflette sull'efficacia della scrittura come cura;

- Il fumo
  Zeno manifesta la caratteristica tipica del nevrotico mentre racconta i vari
  tentativi per abbandonare il vizio del fumo. La tendenza del rimandare gli permette
  sempre di assaporare meglio l'"ultima" sigaretta.

- La morte di mio padre
  Zeno racconta una vicenda di ostilità tra padre e figlio nascosta dietro l'amore che
  secondo il senso comune ci dovrebbe essere tra loro. Racconta poi un trauma, ovvero
  un episodio in cui ha ricevuto uno schiaffo dal padre sul letto di morte, forse
  involontario ma che l'ha segnato per sempre.

- La storia del mio matrimonio
  Zeno decide di sposare una delle figlie di Giovanni Malfenti, un uomo d'affari. Prima
  si dichiara a Ada, che però è innamorata di un altro uomo.
  Poi si dichiara ad Alberta, che non è interessata ad un progetto matrimoniale.
  Alla fine sposa la bruttina Augusta, che si rende disponibile ad assisterlo come
  una madre.

- La moglie e l'amante
  Zeno conosce Carla, una ragazza povera molto bella e molto brava a cantare. Si avvicina
  come benefattore ma tra loro nasce una relazione lontano dalla moglie.
  L'ultimo abbraccio con Carla viene sempre rimandato, come con l'ultima sigaretta.
  Alla fine però è lei ad interrompere la relazione dopo aver spiato quella che pensava
  fosse sua moglie ed aver colto tutta la sua sofferenza.

- Storia di un'associazione commerciale
  Il marito di Ada propone a Zeno di fare il contabile nella sua attività commerciale, e
  Zeno accetta. L'azienda però fallisce a causa di Zeno e il congnato si suicida.
  Zeno specula in borsa a suo nome e riesce ad ottenere gran parte del patrimonio perso
  ma compie un lapsus da manuale di psicanalisi e il giorno della sepoltura si trova
  al corteo funebre di uno sconosciuto.

- Psico-analisi
  È strutturato in forma di diario, Zeno riflette sull'esperienza deludente di psicoanalisi,
  afferma di non essere mai stato malato. Il protagonista ha approfittato della guerra
  per fare speculazioni che portarono ad ingenti guadagni. Dedica le ultime pagine
  a considerazioni sulla vita attuale, in cui ogni sforzo per procurarsi la salute è inutile.
  La salute forse può essere recuperata dopo la distruzione della Terra.

Si parla di tempo misto perchè nei nostri ricordi il tempo deriva dall'importanza che diamo.
Zeno è un inetto.

Aveva un complesso di Edipo irrisolto, il rapporto con il padre rimane conflittuale.
Ha difficoltà anche nei rapporti d'amore e anche delle difficoltà sul lavoro, si sente completamente inadeguato.

Al contrario di D'Annunzio, Svevo non c'era un bello stile ma gli interessa solo il contenuto.

** Dottor S.
Il Dottor S. è uno psicanalista e non ha competenze letterarie.
Non è una novella ma un testo breve. Il fatto che sia imprecisa come definizione è simbolo di realismo.

Diagnosi di nevrosi. Fenomeno del transfert negativo. Il paziente trasmette le proprie emozioni negative
sul medico.

Il termine psicanalisi ritorna 4 volte.
Zeno rifiuta la coscienza di sè stesso.
Il linguaggio di Svevo è molto colloquiale.

Lo scambio del funerale.

Il fatto che il narratore sia inattendibile porta alla distruzione del patto narrativo. Patto narrativo = patto
sottinteso tra il narratore ed il lettore. Il lettore durante la lettura sospende la sua incredulità.

Dottor S. potrebbe essere Svevo stesso o Freud (perchè il suo nome è Sigmund) o Zeno stesso (che è il
protagonista) perchè la S specchiata diventa Z.

Narratori del primo e del secondo livello:
- Dottor S.
- Zeno

** Svevo decide di sposare una delle figlie di Giovanni
Il suo contendente sapeva suonare il violino molto meglio.

Nel 1937 Zeno fa una proposta di matrimonio perchè era nervoso.
La famiglia aveva già deciso che la moglie giusta per Zeno era Augusta perchè era brutta e non l'avrebbe
voluta nessuna.

Zeno è rozzo.

Inizia a capire che la sua ansia deriva dal fatto che vuole rimanere in quella famiglia, anche se Ada l'ha
rifiutato. Pur di rimanere, chiede ad Augusta con una proposta orribile. Lei accetta comunque perchè ha
l'istinto materno.

I nomi delle sorelle iniziano tutti con l'A che è l'opposto del suo che inizia con la Z. Si fa tanto riferimento
alla sanità delle ragazze. Anna, Alberta, Ada ed Augusta.

Ambivalenza del rapporto con Guido => Narratore inattendibile o schizofrenico.
Ha capito che per avere pace quella notte deve rimanere in casa "Malzetti".

Il suo inconscio lo convince ad agire.

Tema della sostituzione del padre. Totale inettitudine di Zeno nei rapporti con gli altri.
