#+title: Italo Svevo

** Italo Svevo
Italo Svevo era un sinonimo di Schmitz. Metà italiano e metà Svevo.
Lavora in banca. Non ha una carriera da letterato, è autodidatta.
Sposa Lidia Veneziani e lavora alla società di vernici del suo padre.

Scrive due romanzi che però non hanno successo.
Pubblica la coscienza di Zeno che ha un grande successo e risente delle teorie di Freud.
Il suo romanzo viene appoggiato da Eugenio Montale.

** La teoria di Freud
Freud è il primo a teorizzare l'inconscio. Nella nostra mente c'è una scatola nera e quando.
Secondo Freud, le cose emergono dall'inconscio grazie ai lapsus.
Per Freud la psiche si divide in tre parti: es, io, super io. I bambini nascono solo con l'es.
Se siamo più verso l'es cerchiamo il nostro piacere, mentre al contrario siamo persone estremamente
rigide. Prime di Freud si pensava che le malattie psicologiche andassero curate fisicamente.

** Una vita e Selenità
Il primo protagonista, Alfonso Nitti. Un giovane che lavora in banca ed è appassionato di letteratura.
Vorrebbe sposare la figlia del suo capo. Alla fine si suicida.

Nei suoi romanzi c'è sempre un protagonista inetto ed un antagonista che è l'opposto.

** Selenità
Protagonista: Stefano Balli, inetto.
Emilio è l'amico antagonista completamente all'opposto del protagonista. Emilio nonostante avesse
una vita molto monotona, invidia il protagonista. Però Angiolina preferisce Stefano perchè era
più affascinante.

Una donna è innamorata e si ammala di polmonite.

Svevo ci sta parlando di protagonisti inetti che non si vogliono lasciar andare a nessuna passione
e piuttosto rinuncia a vivere. Siamo agli antipodi rispetto alla letteratura romantica di Foscolo.
Non vogliono sentire nè il peso nè i rischi delle passioni.

** La coscienza di Zeno
Scritto nel 1923, dopo diversi anni dai precedenti. Ambientato a Trieste, come gli altri due romanzi.
Il protagonista è Zeno Cosini. Il romanzo si percorre per percorsi tematici. È un diario scritto per il
suo psicanalista.

Primo tema: quello del fumo. Il protagonista racconta come ha iniziato a fumare.
Altro tema: il matrimonio.
Si parla di tempo misto perchè nei nostri ricordi il tempo deriva dall'importanza che diamo.
Zeno è un inetto.

Aveva un complesso di Edipo irrisolto, il rapporto con il padre rimane conflittuale.
Ha difficoltà anche nei rapporti d'amore e anche delle difficoltà sul lavoro, si sente completamente inadeguato.

Al contrario di D'Annunzio, Svevo non c'era un bello stile ma gli interessa solo il contenuto.
