#+title: Giacomo Leopardi
#+tags: Natura, Pessimismo, Riflessioni, Politica, Immaginazione, Fratellanza

* La sua vita
Leopardi è nato a Recanati nel 1798, un piccolo borgo di provincia in uno Stato retrogrado dal punto di
vista industriale. La famiglia di Leopardi era nobile, ma il padre (conservatore, vuole proteggere
la famiglia) non era bravo a gestire i soldi e diede l'economia familiare in gestione alla moglie,
una donna fredda e non affettuosa.

Leopardi cresce con una voglia di amore e nello studio riesce ad aprire i suoi orizzonti.
Per sette lunghissimi anni si immerge in uno "studio matto e disperatissimo". Lo stare in casa accentuò
il suo aspetto fisico, il morbo si sviluppò sempre di più. Acquistò una coonoscienza eccezionale
delle lingue antiche e scrisse molte opere, anche grazie alla biblioteca del padre.

Si innamora di una donna di nome Teresa. Ad un certo punto muore e prende spunto da questa
esperienza traumatica per parlarne all'interno dello Zibaldone. Secondo lui, aveva un non
so che di divino che niente può eguagliare.

Nel 1819 tenta di fuggire ma viene scoperto dai propri genitori. Tra il 1819 e il 1822 c'è
la prima stagione poetica perchè scrive i piccoli Idilli e l'Infinito. Nel 1822 fa un viaggio
a Roma ma ne rimane deluso, specialmente dagli intellettuali da cui si ritiene più avanti.

Inizia l'amicizia con Pietro Giordano.

Entra nel vivo della vita intellettuale a Bologna e Firenze.

All'interno di un caffè di innamora di una donna che però amava solo i suoi scritti e non
la persona. Era innamorata invece del suo amico.

* Il suo pensiero
Secondo Leopardi, nulla può soddisfare.
Il fine della vita di Leopardi è quello di raccontarci le *sofferenze* e gli ostacoli che tutti gli uomini vivono.
Non si rifugia nella delusione ma rivendica l'importanza della felicità.
L'uomo ricerca costantemente il piacere materiale, ma tutto risulta temporaneo e parziale. Tutto ci lascia sempre
soddisfatti.

** Pessimismo individuale
Riguarda solo le condizioni di cui soffre *personalmente*.

** Pessimismo storico
Per tutta la vita si è chiesto per quale motivo l'*uomo sia infelice*.
Inizialmente riteneva che fosse colpa del *progresso*. Questa teoria viene chiamata
*pessimismo storico* perchè trova la causa dell'infelicità dell'uomo in un periodo storico.
Gli antichi secondo lui erano i più felici perchè avevano un rapporto *diretto con la natura*.

** Pessimismo cosmico
Crescendo, il suo *pessimismo è aumentato*. Leopardi così trovò un'altra causa dell'infelicità
dell'uomo, ovvero il la *natura* stessa. Il male quindi è ovunque, in ogni aspetto della vita
dell'uomo. La natura non punta alla felicità del singolo, ma alla *continuità della specie*.

** La ginestra
L'uomo deve riscoprire un senso di solidarietà, gli uomini devono allearsi tra di loro per
supportarsi a vicenda contro il dolore provocato dalla natura.

* La poetica
L'uomo ha a disposizione uno strumento potentissimo, ovvero *l'immaginazione*. Ad esempio la *siepe* dell'Infinito.
La poesia di Leopardi è piena di parole che permettono di stimolare l'immaginazione.
Tema della rimembranza => la poesia deve farci ricordare tutte quelle cose che ci hanno resi felici.

Spesso non usa le rime.

* Le sue opere
*** Gli Idilli, tra cui l'Infinito:
  Opere in cui l'autore esprime *riflessioni e pensieri relativi alla natura*. Sono di carattere *colloquiale*.
  Esemplare è l’Infinito, in cui compare una meditazione lirica sull’idea di infinito creato dall’immaginazione,
  a partire da sensazioni visive e uditive.

- Il sabato del villaggio

- Lo Zibaldone:
  Il suo diario personale, scritto in prosa, annota riflessioni, pensieri ed appunti su amore,
  filosofia e politica senza un ordine preciso.

- Le operette morali:
  La sua opera in prosa più importante, contiene 24 dialoghi tra personaggi reali o immaginari in cui
  esprime le proprie convinzioni filosofiche sulla condizione umana.

**** Il cantico del Gallo Silvestre
Leopardi afferma di aver trovato un cantico *scritto in lingua orientale* e di averlo tradotto per una più
semplice comprensione.

Secondo la tradizione popolare, *il Gallo Silvestre è in grado di parlare*.
Il canto sveglia gli uomini incoraggiandoli a vivere, pur sapendo della situazione di dolore di sconforto
nella quale versano gli esseri umani. L'universo ha un ruolo fondamentale nella vita dell'uomo che
contribuisce nel peggiorarla. Il momento del mattino è il momento più sereno, ed è in contrapposizione
alla sera che viene associata alla vecchiaia, espressione della morte.

Il sonno è qualcosa di bello che ci permette di trovarci in un mondo falso, quello dei sogni.
C'è anche una similitudine alle stagioni, primavera ed estate sono stagioni piacevoli per il gallo, mentre
autunno ed inverno sono stagioni negative per lui.
