#+title: Il decadentismo: Pascoli e d'Annunzio

* La corrente del decadentismo
Si tratta di una corrente letteraria nata in Francia alla fine del 1800.
Si caratterizza dal rifiuto del razionalismo e della visione del mondo scientifica.
Lo scrittore deve svelare il mistero che si svela dietro le cose, ricercando ossessivamente la
bellezza.

* Lo stile
Il decadentismo ha dei versi musicali e delle parole magiche e ricche di suggestioni simboliche.
Ricco anche di figure retoriche. Si afferma anche in Italia con Giovanni Pascoli e Gabriele
d'Annunzio.

* Pascoli: il mistero nascosto nella quotidianità
** Vita
Nasdce in Romagna da una famiglia borghese.
La sua giovinezza viene segnata da molti lutti familiari. Questo avvenimento gli procura una ferita
che caratterizza le sue opere. A Bologna è allievo di Carducci.

Vive con le due sorelle con le quali si instaura un legame molto intenso ed esclusivo.

** Temi principali
I temi principali sono le sue vicende personali, associate all'ambiente naturale della Romagna e
della civiltà contadina.

*** La poetica del fanciullino
Come un bambino coglie le piccole cose della natura con stupore e meraviglia, cogliendo il mistero
ed il senso della vita.

*** Tematica del nido
Come senso di protezione e di rifugio. Dopo la morte dei suoi parenti si fissa con l'idea di voler
ricostruire il nido familiare.

** Stile delle sue opere
I versi sono brevi e spezzati, la sintassi è semplice. Le parole hanno una musicalità, onomatopee che 
riproducono i suoni della natura. Non usa la forma del sonetto ma non si sofferma su una metrica regolare,
provandone diverse, come ad esempio rime, pause ed enjambement.
Si alternano termini ricercati ma anche parole di uso comune, che possono essere tecniche e scientifiche o dialettali.

** Il fanciullino
La sua riflessione ruota attorno al fanciullo eterno, 

** Raccolta delle Myricae
*** Lavandare
Si tratta di un Madrigale.

La vista dell'aratro abbandonato ci ricorda l'esperienza umana dell'abbandono e della perdita del nido 
con la nostra famiglia. L'uomo è destinato alla solitudine e all'abbandono.

Mentre i campi sono avvolti dalla nebbia, dal canale arriva il rumore d'acqua che fanno le lavandaie.
Si riesce a scorgere un aratro abbandonato. Dominano i colori spenti.
Ricco di sensazioni uditive perchè vengono descritti il suono dei panni, del canto delle lavandaie.
Il ritmo è lento.

*** L'Assiuolo
Pascoli utilizza frasi circolari, infatti ogni strofa termina con il verso "chiù".

Con questa poesia Pascoli descrive un paesaggio notturno dove all’inizio prevale il sentimento dell’estasi, difatti dice che la notte è meravigliosa, il cielo è chiaro come l’alba e perfino gli alberi sembrano sporgersi per vedere meglio la luna che è nascosta tra le nubi. Il paesaggio descrittivo è reso ancora più incantevole dalla melodia del mare e dai fruscii dei cespugli che sembrano quasi rasserenare l’anima. Tutto quest’ambiente è disturbato non dai lampi, dalle nubi e dalla nebbia, ma solamente da una voce triste che si leva nei campi: il chiù. Una voce che all’apparenza sembra di passaggio, ma di strofa in strofa diventa più angoscioso, fino ad arrivare ad un pianto di morte. Questo suono, per lui, è come un sussulto, una scossa al cuore che gli fa emergere ricordi tristi e pensieri tormentati.

Il suono dell’uccello notturno pare quasi la voce stessa del suo cuore angosciato.

Con tutto il suo componimento poetico, Pascoli vuole esprimere l’incombere dei ricordi e della morte, che impedisce al poeta di godere pienamente la magia di una notte di luna perché è avvolto dal mistero e dall’angoscia della morte.

PROBLEMATICA AFFRONTATA

I principali problemi che il poeta affronta sono il mistero e l’angoscia della morte.

Contribuiscono a creare un’atmosfera di mistero il contrasto tra immagini minacciose e serene. Questo tema è caratterizzato dalla domanda che il poeta fa: “tintinni a invisibili porte: che forse non si aprono più?”. L’interrogazione che Pascoli pone, mette in rapporto il dato fisico, cioè il suono delle cavallette, con una realtà metaforica, ovvero le invisibili porte, aprendosi, potrebbero spiegare il mistero della vita.

Il passaggio dal suono reale alla sua interpretazione metaforica, è molto importante perché apre una riflessione sulla morte e sull’impossibilità per l’uomo di affidarsi alla speranza di un'altra vita dopo la fine dell’esistenza. Questa sensazione negativa è data dalla voce dell’uccello notturno, che per le credenze popolari di allora è considerato un annuncio di disgrazia e di morte.

Durante tutto il nostro percorso, per l’analisi della poesia L’assiuolo, abbiamo notato che il tema dominante, oltre al mistero, è la morte.

Questo tema ricorre spesso nelle sue liriche, non solo come riflesso dei numerosi lutti famigliari supportati nell’infanzia, ma anche dal desiderio d’evasione dalla minacciosa realtà contemporanea e dall’oppressione della società.

La sua precoce esperienza di dolore e di morte aveva influito sulla sua visione pessimista e malinconica della vita e del mondo. Il nostro poeta, molto spesso, per allontanarsi da questa sofferenza cerca di rinchiudersi nel piccolo mondo degli affetti familiari, ovvero il “nido familiare”.

Ogni singolo elemento della natura, descritto nell’assiuolo, è osservato con gli occhi ingenui del fanciullino.

Il fanciullino è un famoso saggio scritto da Pascoli dove lui stesso, espone la sua concezione poetica. Egli afferma che il poeta è chi riesce a vedere le cose con la stessa ingenuità di un bambino. Il poeta quindi non si dovrà inventare la poesia, ma la scoprirà attraverso la sua capacità di cogliere le piccole cose con l’intuizione e non sulla ragione, avendo in questo modo una concezione del mondo che si ha durante l’infanzia.

Pascoli, quindi, cerca rifugio nell’infanzia perché è l’unico momento possibile di felicità.

** X Agosto
Il giorno in cui il padre di Pascoli fu assassinato. Poesia scritta diversi anni dopo il suo omicidio.
Paragona l'episodio dell'uccisione del padre con quello di una rondine che viene uccisa in volo mentre
ritornava al tetto per portare il cibo ai suoi piccoli, come un uomo che ritorna nel suo nido famigliare.
Il 10 Agosto è anche la notte di San Lorenzo che secondo la tradizione popolare è stato arso vivo
su una graticola, nella quale si possono osservare le stelle cadenti.
Pascoli interpreta il cadere delle stelle cadenti come un pianto del cielo, proprio per l'uccisione
del padre.

*** Tema del perdono
La vittima, prima di morire, perdona il suo uccisore. Tema ricorrente nella poetica di Pascoli.

** Temporale
Si tratta di un trittico dedicato ai fenomeni atmosferici. 
Come un pittore, Pascoli dipinge la natura che lo circonda.
Centrale è il tema dei colori.

* D'Annunzio: il culto della bellezza
** Vita
Studia lettere a Roma e vive fuori dagli schemi e nel lusso, accumulando molti debiti. Scappa in 
Francia ed al suo ritorno diventa deputato. Fu un forte nazionalista e sostenitore dell'ingresso 
per l'Italia nella prima guerra mondiale e partecipò all'occupazione militare di Fiume dopo 
la conclusione del conflitto.

Alla fine si ritira nella sua villa sul lago di Garda.

** La poetica: Decadentismo
In questo periodo, d'Annunzio percepisce la crisi della società e dei valori, perde sfiducia per il
progresso.

** La poetica: Estetismo
In questo periodo della sua vita si rifugia in un mondo artificiale fatto solo di bellezza esteriore,
ignorando completamente quella interiore. Le sue opere sono caratterizzate da una bellezza estetica
ma non necessariamente da una contenutistica.

Pratica anche esibizioni teatrali.

** Lo stile
La forma per d'Annunzio è tutto, i contenuti non hanno importanza. Il suo stile è caratterizzato da
musicalità, rime, l'effetto sonoro delle parole, il costante innalzamento del tono, un lessico raro
ed arcaico ed il verso libero.

** Principali opere
*** Il piacere
**** Lo stile
Considerato il più significativo della corrente del decadentismo italiano.

Il romanzo è ricco di latinismi, arcaismi e figure retoriche.
La narrazione avviene in terza persona, il narratore è onniscente e critica
in modo spietato il protagonista. Si tratta di un testo molto autobiografico.

Il protagonista è il conte Andrea Sperelli, un giovane e nobile esteta, intellettuale e piacente.
Vuole mettere in pratica l'insegnamento che gli ha lasciato il padre prima di morire, ovvero
"fare della propria vita un'opera d'arte" ma fallirà perchè non sa mettere in pratica un altro
principio, "habere non haberi", ovvero "possedere ma non essere posseduto".

Vorrebbe produrre un'opera d'arte che sia un capolavoro puro e trovare una donna che possa
aiutarlo a raggiungere il piacere.

**** Trama
Spirelli è in attesa di Elena Muti, donna molto erotica, che aveva trovato un nuovo
amante inglese e ricco. Intanto Spirelli aveva frequentato sette donne, alcune delle quali
sposate, e dopo essere stato scoperto da un marito viene sconfitto a duello.

Durante la convalescenza, aveva riscoperto l'amore per l'arte ed una vita più tranquilla.
Qui conosce Maria, moglie di un diplomatico del Guatemala, l'esatto opposto di Elena Muti, una
donna pura.

Le due donne si alternano nella vita del protagonista.
Elena di Troia, la vergine Maria.

Andrea non riesce a decidere tra le due donne e capisce di essere alla ricerca di una terza
donna, la fusione tra Elena e Maria.

Maria alla fine si concede ma deve fuggire nel Guatemala. Nell'ultimo incontro compie un errore,
quando la donna si sta lasciando andare, spirelli la chiama con il nome di Elena, facendola fuggire.

Nel frattempo anche Elena lo rifiuta ed Andrea si trova solo.
Andrea si reca nella casa di Maria in cui si sta svolgendo un'asta per vendere tutti gli immobili
e pagare i debiti. Il protagonista è inorridito vedere l'arte profanata da facchini e senza un motivo
razionale acquista l'armadio.

Alla fine segue i facchini che portano l'armadio a casa sua. L'armadio gigante ma completamente vuoto
simboleggia ciò che è rimasto delle due donne, ingombrante ed inutile.


*** La sera fiesolana
Composta nell'estate del 1899 e costituisce la prima parte dell'Alcyone.

L'autore rievoca l'esperienza di San Francesco d'Assisi, per questo sceglie come genere la lauda, e
prende spunto dal Cantico delle Creature da cui riprende il motivo "Laudato si', mi' Signore" ma in un
contesto laico.

Ci sono tre strofe e dopo ogni strofa una lauda in tre versi rivolta alla sera. Si trovano anche molte
alliterazioni ed enjambement.

L'ambientazione è il paesaggio toscano, dove era situata la sua abitazione, in una serata di giugno 
dopo la pioggia, alla fine della primavera e l'inizio dell'estate. Il poeta descrive il momento del 
crepuscolo, con la sera e la natura che fanno da protagoniste. Si tratta di un momento di metamorfosi,
come la sera muore spegnendosi lentamente nella notte, la primavera muore trasformandosi in estate.

Sia la sera che tutti gli elementi della natura sono personificati in creature terrene, e la presenza umana
è ridotta al minimo.
La sera rappresenta l'attesa del rapporto d'amore con la propria donna. Dopo la sera infatti ci sarà
un rapporto d'amore.

Nella seconda strofa inesiste sull'idea dell'acqua e sui momenti di passaggio, con il grano che non è ancora
maturo ma non è nemmeno verde.

Nella terza strofa esalta l'innamoramento, in cui le parole non servono a descrivere ma ad evocare.
Si percepisce una sensualità panica, derivato dal panismo, concezione pagana.

Il lessico è ricco di parole arcaiche.
