#+title: Il decadentismo: Pascoli e d'Annunzio

* La corrente del decadentismo
Si tratta di una corrente letteraria nata in Francia alla fine del 1800.
Si caratterizza dal rifiuto del razionalismo e della visione del mondo scientifica.
Lo scrittore deve svelare il mistero che si svela dietro le cose, ricercando ossessivamente la
bellezza.

* Lo stile
Il decadentismo ha dei versi musicali e delle parole magiche e ricche di suggestioni simboliche.
Ricco anche di figure retoriche. Si afferma anche in Italia con Giovanni Pascoli e Gabriele
d'Annunzio.

* Pascoli: il mistero nascosto nella quotidianità
** Vita
Nasdce in Romagna da una famiglia borghese.
La sua giovinezza viene segnata da molti lutti familiari. Questo avvenimento gli procura una ferita
che caratterizza le sue opere. A Bologna è allievo di Carducci.

Vive con le due sorelle con le quali si instaura un legame molto intenso ed esclusivo.

** Temi principali
I temi principali sono le sue vicende personali, associate all'ambiente naturale della Romagna e
della civiltà contadina.

*** La poetica del fanciullino
Come un bambino coglie le piccole cose della natura con stupore e meraviglia, cogliendo il mistero
ed il senso della vita.

*** Tematica del nido
Come senso di protezione e di rifugio. Dopo la morte dei suoi parenti si fissa con l'idea di voler
ricostruire il nido familiare.

** Stile delle sue opere
I versi sono brevi e spezzati, la sintassi è semplice. Le parole hanno una musicalità, onomatopee che 
riproducono i suoni della natura. Non usa la forma del sonetto ma non si sofferma su una metrica regolare,
provandone diverse, come ad esempio rime, pause ed enjambement.
Si alternano termini ricercati ma anche parole di uso comune, che possono essere tecniche e scientifiche o dialettali.

** Il fanciullino
La sua riflessione ruota attorno al fanciullo eterno, 

** Raccolta delle Myricae
*** Lavandare
La vista dell'aratro abbandonato ci ricorda l'esperienza umana dell'abbandono e della perdita del nido con la nostra
famiglia. L'uomo è destinato alla solitudine e all'abbandono.

Dal canale arriva il rumore d'acqua che fanno le lavandaie.

** X Agosto
Il giorno in cui il padre di Pascoli fu assassinato. Poesia scritta diversi anni dopo il suo omicidio.
Paragona l'episodio dell'uccisione del padre con quello di una rondine che viene uccisa in volo mentre
ritornava al suo nido.
Il 10 Agosto è anche la notte di San Lorenzo, nella quale si possono osservare le stelle cadenti.

* D'Annunzio: il culto della bellezza
** Vita
Studia lettere a Roma e vive fuori dagli schemi e nel lusso, accumulando molti debiti. Scappa in 
Francia ed al suo ritorno diventa deputato. Fu un forte nazionalista e sostenitore dell'ingresso 
per l'Italia nella prima guerra mondiale e partecipò all'occupazione militare di Fiume dopo 
la conclusione del conflitto.

Alla fine si ritira nella sua villa sul lago di Garda.

** La poetica: Decadentismo
In questo periodo, d'Annunzio percepisce la crisi della società e dei valori, perde sfiducia per il
progresso.

** La poetica: Estetismo
In questo periodo della sua vita si rifugia in un mondo artificiale fatto solo di bellezza esteriore,
ignorando completamente quella interiore. Le sue opere sono caratterizzate da una bellezza estetica
ma non necessariamente da una contenutistica.

Pratica anche esibizioni teatrali.

** Lo stile
La forma per d'Annunzio è tutto, i contenuti non hanno importanza. Il suo stile è caratterizzato da
musicalità, rime, l'effetto sonoro delle parole, il costante innalzamento del tono, un lessico raro
ed arcaico ed il verso libero.

** Principali opere
*** Il piacere
*** Alcyone
