#+title: Il decadentismo: Pascoli e d'Annunzio

* La corrente del decadentismo
Si tratta di una corrente letteraria nata in Francia alla fine del 1800.
Si caratterizza dal rifiuto del razionalismo e della visione del mondo scientifica.
Lo scrittore deve svelare il mistero che si svela dietro le cose, ricercando ossessivamente la
bellezza.

* Lo stile
Il decadentismo ha dei versi musicali e delle parole magiche e ricche di suggestioni simboliche.
Ricco anche di figure retoriche. Si afferma anche in Italia con Giovanni Pascoli e Gabriele
d'Annunzio.

* Pascoli: il mistero nascosto nella quotidianità
** Vita
Nasdce in Romagna da una famiglia borghese.
La sua giovinezza viene segnata da molti lutti familiari. Questo avvenimento gli procura una ferita
che caratterizza le sue opere. A Bologna è allievo di Carducci.

Vive con le due sorelle con le quali si instaura un legame molto intenso ed esclusivo.

** Temi principali
I temi principali sono le sue vicende personali, associate all'ambiente naturale della Romagna e
della civiltà contadina.

*** La poetica del fanciullino
Come un bambino coglie le piccole cose della natura con stupore e meraviglia, cogliendo il mistero
ed il senso della vita.

*** Tematica del nido
Come senso di protezione e di rifugio. Dopo la morte dei suoi parenti si fissa con l'idea di voler
ricostruire il nido familiare.

** Stile delle sue opere
I versi sono brevi e spezzati, la sintassi è semplice. Le parole hanno una musicalità, onomatopee che 
riproducono i suoni della natura. Non usa la forma del sonetto ma non si sofferma su una metrica regolare,
provandone diverse, come ad esempio rime, pause ed enjambement.
Si alternano termini ricercati ma anche parole di uso comune, che possono essere tecniche e scientifiche o dialettali.

** Il fanciullino
La sua riflessione ruota attorno al fanciullo eterno, 

** Raccolta delle Myricae
*** Lavandare
La vista dell'aratro abbandonato ci ricorda l'esperienza umana dell'abbandono e della perdita del nido con la nostra
famiglia. L'uomo è destinato alla solitudine e all'abbandono.

Dal canale arriva il rumore d'acqua che fanno le lavandaie.

** X Agosto
Il giorno in cui il padre di Pascoli fu assassinato. Poesia scritta diversi anni dopo il suo omicidio.
Paragona l'episodio dell'uccisione del padre con quello di una rondine che viene uccisa in volo mentre
ritornava al tetto per portare il cibo ai suoi piccoli, come un uomo che ritorna nel suo nido famigliare.
Il 10 Agosto è anche la notte di San Lorenzo che secondo la tradizione popolare è stato arso vivo
su una graticola, nella quale si possono osservare le stelle cadenti.
Pascoli interpreta il cadere delle stelle cadenti come un pianto del cielo, proprio per l'uccisione
del padre.

*** Tema del perdono
La vittima, prima di morire, perdona il suo uccisore. Tema ricorrente nella poetica di Pascoli.

** Temporale
Si tratta di un trittico dedicato ai fenomeni atmosferici. 
Come un pittore, Pascoli dipinge la natura che lo circonda.
Centrale è il tema dei colori.

* D'Annunzio: il culto della bellezza
** Vita
Studia lettere a Roma e vive fuori dagli schemi e nel lusso, accumulando molti debiti. Scappa in 
Francia ed al suo ritorno diventa deputato. Fu un forte nazionalista e sostenitore dell'ingresso 
per l'Italia nella prima guerra mondiale e partecipò all'occupazione militare di Fiume dopo 
la conclusione del conflitto.

Alla fine si ritira nella sua villa sul lago di Garda.

** La poetica: Decadentismo
In questo periodo, d'Annunzio percepisce la crisi della società e dei valori, perde sfiducia per il
progresso.

** La poetica: Estetismo
In questo periodo della sua vita si rifugia in un mondo artificiale fatto solo di bellezza esteriore,
ignorando completamente quella interiore. Le sue opere sono caratterizzate da una bellezza estetica
ma non necessariamente da una contenutistica.

Pratica anche esibizioni teatrali.

** Lo stile
La forma per d'Annunzio è tutto, i contenuti non hanno importanza. Il suo stile è caratterizzato da
musicalità, rime, l'effetto sonoro delle parole, il costante innalzamento del tono, un lessico raro
ed arcaico ed il verso libero.

** Principali opere
*** Il piacere

*** La sera fiesolana
Composta nell'estate del 1899 e costituisce la prima parte dell'Alcyone.

L'autore rievoca l'esperienza di San Francesco d'Assisi, per questo sceglie come genere la lauda, e
prende spunto dal Cantico delle Creature da cui riprende il motivo "Laudato si', mi' Signore" ma in un
contesto laico.

Ci sono tre strofe e dopo ogni strofa una lauda in tre versi rivolta alla sera. Si trovano anche molte
alliterazioni ed enjambement.

L'ambientazione è il paesaggio toscano, dove era situata la sua abitazione, in una serata di giugno 
dopo la pioggia, alla fine della primavera e l'inizio dell'estate. Il poeta descrive il momento del 
crepuscolo, con la sera e la natura che fanno da protagoniste. Si tratta di un momento di metamorfosi,
come la sera muore spegnendosi lentamente nella notte, la primavera muore trasformandosi in estate.

Sia la sera che tutti gli elementi della natura sono personificati in creature terrene, e la presenza umana
è ridotta al minimo.
La sera rappresenta l'attesa del rapporto d'amore con la propria donna. Dopo la sera infatti ci sarà
un rapporto d'amore.

Nella seconda strofa inesiste sull'idea dell'acqua e sui momenti di passaggio, con il grano che non è ancora
maturo ma non è nemmeno verde.

Nella terza strofa esalta l'innamoramento, in cui le parole non servono a descrivere ma ad evocare.
Si percepisce una sensualità panica, derivato dal panismo, concezione pagana.

Il lessico è ricco di parole arcaiche.
