#+title: Pirandello
#+created: <2022-04-29 Fri>

** La vita
Nasce ad Agrigento. Studia lettere, prima a Roma e poi in Germania. Lavora
nelle miniere di zolfo. Ad un certo punto la miniera si allaga e perdono
un sacco di soldi.

La moglie ha una grave psicosi e viene internata in un ospedale psichiatrico.
Lui è costretto oltre a scrivere romanzi anche a lavorare nell'università
di Roma e fa anche collaborazioni con i giornali.

Ha pensato che il fascismo potesse essere una soluzione, anche se poi si
è allontanato da quelle idee, senza mai rinnegarle.

** Il suo pensiero
La verità per Pirandello è come un magma indistinto. La società cerca di
dargli una forma che senza queste regoli sociali sarebbe un caos.
Gli dà una forma attraverso tutte le regole sociali, le norme e le convinzioni.
Come se in qualche modo andasse ad imprigionarla. Per Pirandello
nessuna forma di aggregazione corrisponde alla salvezza.

Dissesto economico, follia e prigione familiare diventano allora temi
centrali delle sue opere, oltre alla delusione rispetto alle attese che
aveva nel rinascimento.

Si contrappone a Pascoli. Un concetto fondamentale per Pirandello sono le
maschere. Secondo lui c'è una maschera che indossiamo con la famiglia, una
maschera che indossiamo con il lavoro. Ad esempio, la famiglia impone la
monogamia, a discapito dell'istinto.
L'individuo cambia in base alle altre persone con cui si relaziona.

Vede un uomo claustrofobico e paradossale, che non può mai essere sè stesso
perchè non c'è un solo io, ma tante forme e maschere in cui
è imprigionato. Ma non è nemmeno pessimista perchè coglie gli aspetti
più divertenti creando sia una riflessione che il sorriso.
Ci mostra come si può "prenderla con filosofia".

** La differenza tra umorismo e comicità
Secondo Pirandello, si ha l'umorismo quando si va a vedere il motivo delle azioni,
mentre la comicità quando ci si sofferma solo sull'apparenza.

** La vecchia imbellettata
Vedo questa vecchia vestita come una giovane, all'inizio mi fa ridere ma
poi mi fa pena perchè non voglio che suo marito la tradisca.
Differenza tra qualcosa e qualcos altro (su Teams forse).

** Personaggi di Pirandello
Sempre un uomo intrappolato nella sua vita, oppresso dal lavoro e dalla famiglia.
Non sono in grado di modificare la loro condizione, è qui che nasce la figura
dell'inetto, un uomo incapace di stare al mondo e vivere la propria vita in modo
soddisfacente.
Vuole far riflettere sulla crisi della società e della modernità.

** La novella: il treno ha fischiato
Velluca lavora come ragioniere ed ha un brutto lavoro. È sempre stato molto succube,
un giorno però lavora con il suo capo. La sera si mette sul divano, sente il fischio
del treno e si immagina di essere lì e poter arrivare in altre zone del mondo.
La sua situazione familiare era tragica, c'erano tanti bambini e tante donne ceche,
che però non ci fanno pena perchè vengono disumanizzate.
Alla fine torna al lavoro e chiede ogni tanto delle pause per potersi immaginare
una vita diversa. Dovrebbe farci pena.

Si accorge che c'è una vita diversa rispetto a quella che sta vivendo. È qui che sente
il fischio del treno.
Attraverso l'immaginazione si concede dei brevi momenti di sfogo.

** Lo iettatore
Il giudice gli dice che non avrebbe mai vinto il processo ma lui non ritira la denuncia
perchè voleva la patente da iettatore. Nessuno voleva sposare le figlie per colpa sua.
Con la patente da iettatore pensava di andare davanti ai bar e farsi pagare per andarsene.
Il lettore prova compassione.

** Il fu Mattia Pascal
Si tratta del primo capolavoro di Pirandello, che all'epoca non ottenne molto successo.

Mattia Pascal eredita dal padre una grossa fortuna, ma l'amministratore del suo patrimonio
lo deruba gettandolo sul lastrico.

*** La finta morte
Mattia Pascal fugge a montecarlo dove vince molti soldi, ma quando torna scopre che è
stato dichiarato morto. Decide di cogliere l'occasione per liberarsi di tutte le persone
che conosceva e si trasferisce a Roma come Adriano Meis. Per evitare di essere riconosciuto
si taglia la barba e si fa crescere i capelli.

*** La vita come Adriano Meis
Giunto a Roma, Adriano Meis si innamora di Adriana, la figlia del suo padrone di casa, ma non
può sposarla perchè di fronte alla legge non esiste. Allora decide di fingersi nuovamente
morto per riprendere il suo ruolo di Mattia Pascal.

*** Il ritorno come Mattia Pascal
Ritornando al suo paese originario come Mattia Pascal, scopre che sua moglie si è rifatta
una vita con un altro uomo ed ha anche avuto una figlia. Decide quindi di vivere come
anonimo in una biblioteca in cui scrive la sua storia.


** Perchè è un inetto
Perchè è insoddisfatto della sua vita iniziale. È incapace anche di cambiare vita perchè quando
ci prova fallisce. Alla base c'è il fatto che in entrambi i casi non abbiamo una vera e propria
identità. Per Pirandello non esiste una sola identità, ogni contesto aveva una maschera. Mattia
non riesce a costruirsi un'identità integra nemmeno quando cambia identità.
Non può vivere liberamente.

** Adriano Menis
Mattia Pascal si è tolto la maschera ed è diventato Adriano Menis, solo che non riesce comunque
a farsi una vita dopo il finto suicidio.
Prova a baciare la moglie ma viene derubato di 12 mila lire.
Si chide chi ha più ombra tra lui e lei. Si rende conto che la sua vita è falsa, è ridotta
all'ombra dell'uomo, non ha diritti, la sua identità non esiste.
Cerca di liberarsi dalla sua ombra perchè gli ricorda la sua esistenza, che non è un'esistenza
piena. Gli hanno appena rubato del denaro e non può farci nulla.

"Quell'ombra aveva un cuore e non poteva amare" si riferisce ad Adriana, che ama ma che non può
sposare.

Prova pena per la sua stessa esistenza. Ha trovato una nuova vita che lo intrappona ancora di più
rispetto alla vita precedente.

** Pascal con don Eligio
Nel colloquio con don Eligio si chiede che lezione si possa ricavare dalla situazione che gli è
capitata. Quando è rientrato a Milano ha passato gli ultimi sei mesi a scrivere un romanzo.
Don Eligio gli dice che fuori dalla società non si può vivere. Secondo Don Eligio siamo costretti
ad indossare delle maschere per poter vivere. Pascal gli risponde che non riesce a riacquisire la sua
vecchia vita.

La lapide esprime una verità, la lapide effettiva di Mattia Pascal dice che di fatto è un morto, perchè
non esiste. Anche se è vivo. Si insiste sul tema della morte. Si reca spesso ai piedi della sua tomba,
dove è sepolto un altro uomo.

Il finale è umoristico. Si conclude con "Io fu Mattia Pascal"
