#+title: Pirandello
#+created: <2022-04-29 Fri>

** La vita
Nasce ad Agrigento. Studia lettere, prima a Roma e poi in Germania. Lavora
nelle miniere di zolfo. Ad un certo punto la miniera si allaga e perdono
un sacco di soldi.

La moglie ha una grave psicosi e viene internata in un ospedale psichiatrico.
Lui è costretto oltre a scrivere romanzi anche a lavorare nell'università
di Roma e fa anche collaborazioni con i giornali.

Ha pensato che il fascismo potesse essere una soluzione, anche se poi si
è allontanato da quelle idee, senza mai rinnegarle.

** Il suo pensiero
La verità per Pirandello è come un magma indistinto. La società cerca di
dargli una forma che senza queste regoli sociali sarebbe un caos. In che
senso gli dà una forma? Attraverso tutte le regole sociali, le norme, le
convinzioni. Come se in qualche modo andasse ad imprigionarla. Per Pirandello
nessuna forma di aggregazione corrisponde alla salvezza.

Si contrappone a Pascoli. Un concetto fondamentale per Pirandello sono le
maschere. Secondo lui c'è una maschera che indossiamo con la famiglia, una
maschera che indossiamo con il lavoro. Ad esempio, la famiglia impone la
monogamia, a discapito dell'istinto.
L'individuo cambia in base alle altre persone.

** Boh
Vedo questa vecchia vestita come una giovane, all'inizio mi fa ridere ma
poi mi fa pena perchè non voglio che suo marito la tradisca.
Differenza tra qualcosa e qualcos altro (su Teams forse).

** Personaggi di Pirandello
Sempre un uomo intrappolato nella sua vita, oppresso dal lavoro e dalla famiglia.
Non sono in grado di modificare la loro condizione, è qui che nasce la figura
dell'inetto, un uomo incapace di stare al mondo e vivere la propria vita in modo
soddisfacente.
Vuole far riflettere sulla crisi della società e della modernità.

** La novella: il treno ha fischiato
Velluca lavora come ragioniere ed ha un brutto lavoro. È sempre stato molto succube,
un giorno però lavora con il suo capo. La sera si mette sul divano, sente il fischio
del treno e si immagina di essere lì e poter arrivare in altre zone del mondo.
La sua situazione familiare era tragica, c'erano tanti bambini e tante donne ceche,
che però non ci fanno pena perchè vengono disumanizzate.
Alla fine torna al lavoro e chiede ogni tanto delle pause per potersi immaginare
una vita diversa. Dovrebbe farci pena.

Si accorge che c'è una vita diversa rispetto a quella che sta vivendo. È qui che sente
il fischio del treno.
Attraverso l'immaginazione si concede dei brevi momenti di sfogo.

** Lo iettatore
Il giudice gli dice che non avrebbe mai vinto il processo ma lui non ritira la denuncia
perchè voleva la patente da iettatore. Nessuno voleva sposare le figlie per colpa sua.
Con la patente da iettatore pensava di andare davanti ai bar e farsi pagare per andarsene.
Il lettore prova compassione.

** Mattia Pascal
Ha ereditato dal padre una grossa fortuna. L'amministratore del patrimonio lo deruba gettandolo
sul lastrico. Hanno trovato un corpo nel suo paesello e l'hanno scambiato per lui, così lui fugge e
cambia vita. Per evitare di essere riconosciuto si taglia la barba e si fa crescere i capelli.
Prende in affitto una casa a Roma. Si innamora di Adriana ma non può sposarsi perchè non aveva i
documenti, così finge il suicidio e ritorna Mattia Pascal. Sua moglie si era risposata ed aveva
avuto una bambina. Si ritira ancora come anonimo.

** Perchè è un inetto
Perchè è insoddisfatto della sua vita iniziale. È incapace anche di cambiare vita perchè quando
ci prova fallisce. Alla base c'è il fatto che in entrambi i casi non abbiamo una vera e propria
identità. Per Pirandello non esiste una sola identità, ogni contesto aveva una maschera. Mattia
non riesce a costruirsi un'identità integra nemmeno quando cambia identità.
Non può vivere liberamente.

** Adriano Menis
Mattia Pascal si è tolto la maschera ed è diventato Adriano Menis, solo che non riesce comunque
a farsi una vita dopo il finto suicidio.
Prova a baciare la moglie ma viene derubato di 12 mila lire.
Si chide chi ha più ombra tra lui e lei. Si rende conto che la sua vita è falsa, è ridotta
all'ombra dell'uomo, non ha diritti, la sua identità non esiste.
Cerca di liberarsi dalla sua ombra perchè gli ricorda la sua esistenza, che non è un'esistenza
piena. Gli hanno appena rubato del denaro e non può farci nulla.

"Quell'ombra aveva un cuore e non poteva amare" si riferisce ad Adriana, che ama ma che non può
sposare.

Prova pena per la sua stessa esistenza. Ha trovato una nuova vita che lo intrappona ancora di più
rispetto alla vita precedente.
