#+title: Pirandello
#+created: <2022-04-29 Fri>

** La vita
Nasce ad Agrigento. Studia lettere, prima a Roma e poi in Germania. Lavora
nelle miniere di zolfo. Ad un certo punto la miniera si allaga e perdono
un sacco di soldi. 

La moglie ha una grave psicosi e viene internata in un ospedale psichiatrico.
Lui è costretto oltre a scrivere romanzi anche a lavorare nell'università
di Roma e fa anche collaborazioni con i giornali.

Ha pensato che il fascismo potesse essere una soluzione, anche se poi si
è allontanato da quelle idee, senza mai rinnegarle.

** Il suo pensiero
La verità per Pirandello è come un magma indistinto. La società cerca di
dargli una forma che senza queste regoli sociali sarebbe un caos. In che
senso gli dà una forma? Attraverso tutte le regole sociali, le norme, le
convinzioni. Come se in qualche modo andasse ad imprigionarla. Per Pirandello
nessuna forma di aggregazione corrisponde alla salvezza.

Si contrappone a Pascoli. Un concetto fondamentale per Pirandello sono le
maschere. Secondo lui c'è una maschera che indossiamo con la famiglia, una
maschera che indossiamo con il lavoro. Ad esempio, la famiglia impone la
monogamia, a discapito dell'istinto.
L'individuo cambia in base alle altre persone.
