#+title: Pirandello
#+created: <2022-04-29 Fri>

** La vita
Nasce ad Agrigento. Studia lettere, prima a Roma e poi in Germania. Lavora
nelle miniere di zolfo. Ad un certo punto la miniera si allaga e perdono
un sacco di soldi.

La moglie ha una grave psicosi e viene internata in un ospedale psichiatrico.
Lui è costretto oltre a scrivere romanzi anche a lavorare nell'università
di Roma e fa anche collaborazioni con i giornali.

Ha pensato che il fascismo potesse essere una soluzione, anche se poi si
è allontanato da quelle idee, senza mai rinnegarle.

** Il suo pensiero
La verità per Pirandello è come un magma indistinto. La società cerca di
dargli una forma che senza queste regoli sociali sarebbe un caos. In che
senso gli dà una forma? Attraverso tutte le regole sociali, le norme, le
convinzioni. Come se in qualche modo andasse ad imprigionarla. Per Pirandello
nessuna forma di aggregazione corrisponde alla salvezza.

Si contrappone a Pascoli. Un concetto fondamentale per Pirandello sono le
maschere. Secondo lui c'è una maschera che indossiamo con la famiglia, una
maschera che indossiamo con il lavoro. Ad esempio, la famiglia impone la
monogamia, a discapito dell'istinto.
L'individuo cambia in base alle altre persone.

** Boh
Vedo questa vecchia vestita come una giovane, all'inizio mi fa ridere ma
poi mi fa pena perchè non voglio che suo marito la tradisca.
Differenza tra qualcosa e qualcos altro (su Teams forse).

** Personaggi di Pirandello
Sempre un uomo intrappolato nella sua vita, oppresso dal lavoro e dalla famiglia.
Non sono in grado di modificare la loro condizione, è qui che nasce la figura
dell'inetto, un uomo incapace di stare al mondo e vivere la propria vita in modo
soddisfacente.
Vuole far riflettere sulla crisi della società e della modernità.

** La novella: il treno ha fischiato
Velluca lavora come ragioniere ed ha un brutto lavoro. È sempre stato molto succube,
un giorno però lavora con il suo capo. La sera si mette sul divano, sente il fischio
del treno e si immagina di essere lì e poter arrivare in altre zone del mondo.
La sua situazione familiare era tragica, c'erano tanti bambini e tante donne ceche.
Alla fine torna al lavoro e chiede ogni tanto delle pause per potersi immaginare
una vita diversa. Dovrebbe farci pena.
