#+title: Verga

* La vita
Figlio di proprietari terrieri, nasce a Catania e riceve una formazione romantica.

A Firenze entra in contatto con la vera *società letteraria Italiana*. Poi si trasferisce a Milano
dove entra in contatto con la *Scapigliatura*.

Poi c'è la svolta verso il Verismo, con opere come:
- Rosso Malpelo
- I Malavoglia
- Mastro-don Gesualdo
- La Duchessa de Leyra, che non riesce a portare a termine

Dopo essere tornato a Catania si chiuse in un silenzio tombale.

* Il verismo
Esigenza del vero, il racconto della realtà. Non ci si interessa dei nobili ma degli umili,
storie raccontate da uno scienziato in modo quasi scientifico. *Far emergere la realtà*
che *parla da sola*.

Una visione pessimistica, la vita non fa altro che travolgere i vinti.

* Tecniche narrative
Rappresenta ambienti popolari e rurali, e lo fa con un linguaggio estremamente diverso da quello
dello scrittore borghese.

** Impersonalità
Secondo Verga, ciò che racconta deve sembrare *realmente accaduto*, non si deve vedere il *filtro
dello scrittore*. Lo scrittore deve eclissarsi, non ci devono essere le sue spiegazioni nè
le sue impressioni perchè non ha il diritto di giudicare.

** Discorso indiretto libero

** Narratore regredito
Verga era molto più colto dei protagonisti delle sue opere ma decide di regredire per andare al suo
livello. Ad esempio nell'inizio di rosso malpelo si dice che =aveva i capelli rossi
perchè era un ragazzo malizioso e cattivo= anche se non lo pensava personalmente.

** La lingua
Le opere sono scritte in Italiano perchè devono essere comprensibili a tutte, ma con
anche espressioni del dialetto siciliano.

* Pensiero
Verga sostiene che il progresso sia una fonte di sofferenza. I vinti sono quelli che
non riescono a stare a passo con il progresso.

** Ideale dell'ostrica
Se l'ostrica si stacca dallo scoglio muore. Se noi ci stacchiamo dalla famiglia
e dalle tradizioni moriamo. Per non perderci dobbiamo restare ancorati al nostro sistema di valori.

Verga per descrivere le classi povere della Sicilia ha bisogno di una serie di
documenti, dato che essendo nato in Sicilia da una famiglia di proprietari terrieri,
non ha mai provato sulla sua pelle quello di cui parla.

* I Malavoglia
** Introduzione
I Malavoglia fa parte del primo ciclo dei vinti.
I protagonisti sono una famiglia povera di *pescatori siciliani*, sconfitti nella lotta per
l'affermazione sociale. La vicenza si svolge subito dopo l'unità d'Italia 1865-1875 ad
*Aci Trezza* in provincia di Catania.

Il soprannone "Malavoglia" ha un significato ironico poichè non gli manca di certo la voglia
di lavorare.

Vivono nella casa del nespolo ed hanno una barca chiamata "la provvidenza", anche qui il nome
è ironico.

** Lo stile
Il romanzo è ricco di discorsi diretti con l'utilizzo del discorso diretto ed indiretto libero.
È quindi il lettore che deve capire quale personaggio sta parlando.
Si usa una parlata popolare, spesso con dialetto e modi di dire siciliani.
Ci sono anche figure retoriche come metafore e similitudini tratte dalla vita quotidiana.w:wq


Non c'è giudizio da parte dell'autore. Verga con questo racconto ci sta dicendo che compie
un'indagine scientifica osservando la reazione al progresso da parte di gente umile. Come
si sviluppano i primi turbamenti al pensiero di poter migliorare la propria condizione.

** Personaggi
- Padron 'Ntoni: nonno e capofamiglia, il più vecchio di tutti. Stimato per il suo buonsenso e parla
  sempre con proverbi.
- Bastianazzo: il figlio, grande e grosso ma sottomesso dal padre.
- La Longa: la nuora, chiamata così perchè bassa di statura.
- 'Ntoni, Luca, Messi, Mena e Lia: i nipoti

** La fiumana del progresso
Secondo Verga, il progresso è come un fiume che scorre continuamente. Selezione
naturale, c'è chi resiste e chi viene completamente soppiantato. (riga 5).

** La rivoluzione per la tassa sulla pece
Questo capitolo parla dei dolori e delle scorrettezze che devono subire i poveri quotidianamente.
Hanno messo una tassa sulla pece che colpisce le persone povere. Le donne sono scese in
piazza per protestare contro.

** L'addio di 'Ntoni
'Ntoni, dopo aver accoltellato un uomo perchè aveva avuto un rapporto con sua sorella Lia,
disonorando la morale del tempo, decide di andarsene. Dopo aver trascorso cinque anni in
carcere, torna ad Aci Trezza per salutare la famiglia per l'ultima volta.

Il giovane è costretto a partire per la leva militare. Padron ntoni decide di comprare a
debito dei lupini per poi rivenderli. La barca però naufraga e muoiono in mare. Vende
la barca e vende la casa per ripagare il debito dei lupini.


Verga non andrà avanti con il giro dei vinti perchè diventa sempre più complesso.
Nei malavoglia la ricerca del progresso è una lotta dei bisogni materiali.

I personaggi si presentano da soli, non è il narratore a presentarli.
Appena la famiglia Malavoglia prova ad arricchirsi hanno un debito e perdono tutto.

I malavoglia erano dei grandi lavoratori.
La barca si chiamava provvidenza. La barca naufraga e bastianazzo muore. Da lì inizia il declino.

Verga sostiene che il progresso sia una fonte di sofferenza. I vinti sono quelli che
non riescono a stare a passo con il progresso.
Ideale dell'ostrica: se l'ostrica si stacca dallo scoglio muore. Se noi ci stacchiamo dalla
famiglia e dalle tradizioni moriamo. Per non perderci dobbiamo restare ancorati al nostro sistema di valori.

Verga per descrivere le classi povere della Sicilia ha bisogno di una serie di
documenti. Nasce in Sicilia da una famiglia di proprietari terrieri, non ha mai provato
sulla sua pelle quello di cui parla.

I malavoglia, dei pescatori siciliani. Protagonisti sono i vinti. Il nome dell'intero
ciclo sarebbe stato ciclo dei vinti, avrebbe dovuto rappresentare gli sconfitti nella
lotta dell'affermazione sociale.

Secondo Verga, al top della scala sociale ci sono gli artisti. I pescatori invece
sono al gradino più basso

La vicenza si svolge subito dopo l'unità d'Italia 1865-1875 ad Acitrezza in provincia di Catania.

Bastianaccio aveva sposato Maruzza la Longa

Il giovane è costretto a partire per la leva militare. Padron ntoni decide di comprare a
debito dei lupini per poi rivenderli. La barba però naufraga e muoiono in mare. Vende
la barca e vende la casa per ripagare il debito dei lupini.

MALAVOGLIA: La famiglia era disposta come el dita di una mano.
Il figlio Bastianazzo era grosso. Non era l'antifrasi. Faceva tutto quello che gli veniva detto.
La longa è la moglie di Bastianazzo. Chiamata Longa perchè era corta.
Ntoni era il più giovane, contrario del nonno.
Luca era più giudizioso.
Filomena soprannominata sant'agata perchè stava sempre al telaio. Sant'Agata per
evitare i matrimoni combinati aveva iniziato a tessere un telaio.
Padron Ntoni conosceva dei motti sentiti dagli anziani e parla per proverbi. Verga ne usa molti.

Ntoni sarebbe dovuto andare a fare la leva militare, la famiglia soffre perchè avrebbe avuto bisogno del suo lavoro. Cercano di trovare un cavillo a cui appigliarsi

Esempio di oralità: verga utilizza i proverbi tradotti dal dialetto, e scrive esattamente come parlano "Alla Longa, l'era parso rubato a lei quel saluto". SI anticipa il complemento di termine e c'è un eccesso di pronomi. Ad esempio "a me mi", è un altro eccesso di pronomi. La frase senza eccesso di pronomi sarebbe: "Era parso rubato alla Longa quel saluto".
