#+title: Era fascista

** La vittoria mutilata
Gennaio 19, conferenza di pace di Versailles. L'Italia non ottiene le terre che avrebbe dovuto avere, secondo
un principio di nazionalità. L'Italia rivendica la città di fiume perchè era abitata principalmente da Italiani.
L'Italia (il ministro degli esteri Sonnino) decide di accettare di perdere la Dalmazia.

Si diffonde l'idea di aver vinto la guerra ma perso la pace. Da qui l'espressione di vittoria mutilata. D'Annunzio
occupa Fiume, ed alla fine l'Italia prende Istria.

** Nuovo sistema politico e nascita del PCI
La crisi economica colpisce la piccola e la media borghesia. Inizia una serie di scioperi. Si passa dal sistema
proporzionario ad uno maggioritario. Vanno al governo i grossi partiti di massa, tra cui il partito socialista
ed il partito popolare italiano. Nasce da un sacerdote e decide di creare un partito che si colloca al centro.
Non si rivede nei liberali nè nei socialisti e non si rivolge solo ai cattolici. Gramsci non avrebbe voluto separarsi
dai socialisti perchè sapeva che avrebbe portato alla separazione dei voti. Alla fine però le parole di Lenin
gli fanno cambiare idea. Si decide quindi di separare il partito e nasce il PCI.

** Il partito fascista
Al governo vanno i liberali ed i popolari.
Il movimento di Mussolini in questi anni non voleva nulla, ma ad un certo punto ha una svolta radicale dal socialismo alla destra.

Nel comune di Bologna avevano vinto i socialisti. Al momento dell'insediamento vengono sparati dei colpi di pistola sulla folla
di matrice socialista. Il governo tuttavia non fa nulla, perchè il pericolo principale erano i fascisti per via di una
possibile rivoluzione Bolscevica.

** Elezioni Maggio 1921
I fascisti si presentano in coalizione con liberali e nazionalisti. Adesso i fascisti non sono più così irrilevanti, ed i
fascisti entrano in Parlamento con 35 seggi su 275.
