#+title: Era fascista

** La vittoria mutilata
Gennaio 19, conferenza di pace di Versailles. L'Italia non ottiene le terre che avrebbe dovuto avere, secondo
un principio di nazionalità. L'Italia rivendica la città di fiume perchè era abitata principalmente da Italiani.
L'Italia (il ministro degli esteri Sonnino) decide di accettare di perdere la Dalmazia.

Si diffonde l'idea di aver vinto la guerra ma perso la pace. Da qui l'espressione di vittoria mutilata. D'Annunzio
occupa Fiume, ed alla fine l'Italia prende Istria.

** Nuovo sistema politico e nascita del PCI
La crisi economica colpisce la piccola e la media borghesia. Inizia una serie di scioperi. Si passa dal sistema
proporzionario ad uno maggioritario. Vanno al governo i grossi partiti di massa, tra cui il partito socialista
ed il partito popolare italiano. Nasce da un sacerdote e decide di creare un partito che si colloca al centro.
Non si rivede nei liberali nè nei socialisti e non si rivolge solo ai cattolici. Gramsci non avrebbe voluto separarsi
dai socialisti perchè sapeva che avrebbe portato alla separazione dei voti. Alla fine però le parole di Lenin
gli fanno cambiare idea. Si decide quindi di separare il partito e nasce il PCI.

** Il partito fascista
Al governo vanno i liberali ed i popolari.
Il movimento di Mussolini in questi anni non voleva nulla, ma ad un certo punto ha una svolta radicale dal socialismo alla destra.

Nel comune di Bologna avevano vinto i socialisti. Al momento dell'insediamento vengono sparati dei colpi di pistola sulla folla
di matrice socialista. Il governo tuttavia non fa nulla, perchè il pericolo principale erano i fascisti per via di una
possibile rivoluzione Bolscevica.

** Elezioni Maggio 1921
I fascisti si presentano in coalizione con liberali e nazionalisti. Adesso i fascisti non sono più così irrilevanti, ed i
fascisti entrano in Parlamento con 35 seggi su 275.

** Ascesa dei fascisti
Quando i fascisti entrano in parlamento, gli viene chiesto di cessare le violenze verso gli altri partiti ma l'ala più
violenta non accetta, perciò Mussolini decide di modificare il movimento in partito (Partito Nazionale Fascista)

Il Re non dichiara lo stato di assedio perchè non pensava che Mussolini stesse per instaurare una dittatura, per cui
gli diede il compito di instaurare un governo. La minaccia principale in quegli anni era il comunismo e la
rivoluzione russa. Nel 1923 i popolari si staccano. I fascisti si coalizzano.

Nel momento in cui è al governo gli si chiede di cessare nuovamente le violenze squadriste. Trasforma un esercito di
partito in un esercito di Stato, nazionale.

** La vittoria dei fascisti in parlamento
Ogni partito che avrebbe avuto almeno il 25% dei voti avrebbe avuto i 2/3 del parlamento -> premio di maggioranza.
Servirebbe per governare, fatta dai fascisti. Con questa legge elettorale si fanno le elezioni del 1924.
Mussolini si presenta alle elezioni con delle liste imparentate, però si staccano da lui i liberali di Giolitti.
Socialisti, comunisti e liberali si presentano tutti singolarmente.

Vincono i fascisti con il 65%.

** Omicidio di Matteotti
Matteotti era un parlamentare che denunciò le violenze fasciste nel corso delle elezioni. Questo risveglia
l'opinione pubblica nei confronti dei fascisti. Il potere del partito fascista in questo momento vacilla.

** Secessione dell'Aventino
Non vanno in parlamento per opporsi alle violenze fasciste. Secessione perchè richiama la pratica romana
della secessione. I plebei volevano gli stessi diritti dei patrizi e causavano dei disordini allontanandosi
dalla società.

** Cade la democrazia
Il governo fascista instaura una dittatura e controlla tutti gli aspetti dello Stato.
Il partito fascista proponeva una lista di 400 deputati ed il popolo era chiamato ad approvarla o meno. Non c'era
più la votazione tradizionale.
Nasce il fascio littorio come emblema dello Stato, un simbolo che deriva dall'antica Roma.

** I provvedimenti:
*** Controllo dei mezzi di comunicazione
Mussolini fu il primo a rendersi conto di quanto fossero importanti i mezzi di comunicazione.
Nei cinema si esaltava la dittatura fascista.

*** Aumento della natalità e dei matrimoni, incentivi alle famiglie
Per avere più soldati in futuro. Nelle sagre della nuzialità si sposavano anche 100 persone al giorno.
C'erano anche degli incentivi economici alle famiglie, comprese delle agevolazioni ai lavoratori padri.
Tassa sul celibato: chi non era sposato doveva pagare una tassa.

*** Incentivi allo sport
Per via del culto dell'uomo forte. I giovani venivano divisi in determinate organizzazioni.

*** Controllo della scuola
Si insegna la disciplina militare, il motto "credere, obbedire, combattere". Modifica i manuali scolastici
con l'introduzione di testi fascisti. Ad esempio leggi che sostengono la divisione in razze.

*** Corporatismo
Nel fascismo, la società è più importante dell'individuo. Sotto il fascismo, l'individuo aveva più doveri
nei confronti della società. Si scontra con l'idea socialista della lotta di classe, perchè la lotta di
classe indebolisce la società.

Le corporazioni raggruppavano tutti quelli che facevano lo stesso mestiere, delle unioni di lavoratori.
Si supera la lotta di classe perchè i produttori dovevano andare in contro alle esigenze dei lavoratori
e viceversa. Lo scioero era proibito e si favorivano fortemente i produttori.

*** Cattolicesimo
Si rende conto che l'Italia è estremamente cattolica e che non avrebbe potuto governare contro la chiesa.
Per questo motivo firma i Patti Lateranensi, ovvero un accordo con la Chiesa.

**** I Patti Lateranensi
- La Chiesa riconosce lo Stato;
- Lo Stato paga un indennizzo alla Chiesa;
- La Religione Cattolica viene riconosciuta come religione di Stato ed insegnata nelle scuole;
- Si riconoscono gli effetti civili del matrimonio in chiesa;
- Si concede alla chiesa di nominare i vescovi;

*** Politica economica
La politica economica fascista è protezionistica, non esiste un mercato libero. Mussolini punta
all'autarchia. L'Italia avrebbe dovuto produrre tutto nel proprio Stato, senza importare nulla.
Il problema è che l'Italia non aveva tutte le risorse.

Bonifica l'agro pontino in modo da renderlo coltivabile ed essere autosufficiente nella produzione
del grano.

*** Politica estera
Piuttosto che risollevare l'economia interna, conquista un nuovo territorio (Etiopia).
Qual è il problema della conquista dell'etiopia: c'era una legge che impediva alle altre nazioni di
inviare le armi all'Italia. Mussolini assume un'atteggiamento vittimistico.
In questo modo ottiene il consenso dell'opinione pubblica.
Nel 1936 l'Italia conquista l'Etiopia. Offre la corona a Vittorio Emanuele III. La conquista del territorio
dimostra che l'Italia è potente.

**** Asse Roma-Berlino
Il primo momento di vicinanza tra Hitler e Mussolini. Nel 1938 vengono promulgate le leggi razziali anche
in Italia.
