#+title: Nazismo

** La nascita della Repubblica del 1918
La repubblica si chiama Repubblica di Weimar e nasce l'assemblea costituente, che definisce una
nuova costituzione.
Il potere esecutivo è dato al governo ed in particolar modo ad un cancelliere. Il presidente
della repubblica aveva forti poteri, e veniva eletto dal popolo ogni 7 anni.

La base della Repubblica è social-democratica e riformista. Significa che la maggioranza del
governo è data ai socialisti riformisti e moderati.

** La crisi economica
Dato che dopo la prima guerra mondiale è prevalsa la linea punitiva, la Germania dovette pagare
132 miliardi di marchi alle potenze vincitrici, che portò ad una crisi economica.

Riescono a contenere una rivoluzione comunista.

** Il colpo di Stato di Hitler
Nel 1923 Hitler tenta un colpo di Stato a Monaco e viene imprigionato per pochi mesi.
In prigione scrive il Mein Kampf nel quale critica la democrazia e propone una dittatura con l'espansione
dello spazio vitale ad Est (invasione dell'URSS).
Teorizza l'antisemitismo contro gli ebrei attraverso il mito della purezza ariana.

Nel 1923 come cancelliere al governo c'è Stressman che si pone due obiettivi: economia e dialogo con le
potenze straniere.
Gli Stati Uniti si rendono conto che la Germania non avrebbe mai potuto pagare le riparazioni e quindi
investono capitali nelle fabbriche tedesche.

La Germania viene riammessa al dialogo internazionale.

** Periodo di relativa stabilità
Non c'è stato un piano di ripartenza interno, tutto dipende dagli investimenti americani.
Nel 1935 ci sono le elezioni presidenziali e viene eletto Inderburg.
Nel 1929 crolla la borsa di Wall Street. Le banche prestavano praticamente a tasso zero. Chiunque
poteva richiedere un prestito. Il ceto medio Americano vedeva la possibilità di un guadagno facile
attraverso gli investimenti in borsa. Ciò che fa sì che la valutazione delle aziende aumentasse
molto, facendo staccare dal valore reale.

Il 24 Ottobre 1929 la borsa crolla per questo motivo. Le banche iniziano a chiedere gli interessi ma
gli investitori non riuscivano a trovare acquirenti per le loro azioni. La Germania crolla a sua volta e
gli investimenti cessano.

** L'ascesa di Hitler
La popolazione si estremizza (sia a sinistra che a destra) e i borghesi temono una rivoluzione comunista.
Hitler ed il suo partito nel 1928 avevaono il 2% dei voti. Dopo il crollo di Wall Street, i nazionalsocialisti
salgono al 18%. Hitler afferma che la crisi della Germania è colpa delle potenze vincitrici.
Successivamente prende il 37% diventando il partito più votato.

** Incendio del parlamento
I tedeschi incendiano il parlamento e la colpa ricade sui comunisti. Ciò giustifica un periodo di violenze
contro i comunisti.
Nel marzo del 1933 Hitler prende il 44%. Riesce a formare un governo insieme all'estrema destra.
Successivamente instaura il partito unico.

Nell'agosto del 1934 muore Hindemburg. At Hitler viene assegnato l'incarico di formare un governo.
Al tempo era cancelliere, ma si fa dare anche l'incarico di presidente della Repubblica.

** La notte dei lunghi coltelli
Attraverso la gestapo vengono uccisi.

** Leggi di Norimberga
Nel 1935 con le leggi di Norimberga gli ebrei perdono alcuni diritti civili.

** La notte dei cristalli
Le vetrine dei negozi degli ebrei vengono distrutte.

** Miglioramento della razza
Successivamente vengono colpiti anche disabili, omosessuali, gente con malformazioni ed altre cose.
