#+title: Nazismo

** La nascita della Repubblica del 1918
I tedeschi vogliono uscire dalla guerra, ma il Kaiser non ascolta. Così a Novembre del 1918 viene
proclamata la Repubblica di Weimer, e nasce l'assemblea costituente. La Repubblica di Weimer è
una repubblica socialdemocratica riformista.

Il potere esecutivo è dato al governo ed in particolar modo al cancelliere. Il presidente
della repubblica aveva forti poteri, e veniva eletto dal popolo ogni 7 anni.

La base della Repubblica è social-democratica e riformista. Significa che la maggioranza del
governo è data ai socialisti riformisti e moderati.

** La crisi economica ed i colpi di Stato
Dato che dopo la prima guerra mondiale è prevalsa la linea punitiva, la Germania dovette pagare
132 miliardi di marchi alle potenze vincitrici, che portò ad una forte crisi economica.

Oltre a questo, ci furono anche due tentati colpi di Stato, in particolare uno da parte dei
nazinalsocialisti di Hitler nel 1923.

Riescono a contenere una rivoluzione comunista.

** Il colpo di Stato di Hitler
Nel 1923 Hitler tenta un colpo di Stato a Monaco e viene imprigionato per pochi mesi.
In prigione scrive il Mein Kampf nel quale critica la democrazia e propone una dittatura con l'espansione
dello spazio vitale ad Est (invasione dell'URSS).
Teorizza l'antisemitismo contro gli ebrei attraverso il mito della purezza ariana.

Nel 1923 come cancelliere al governo c'è Stressman che si pone due obiettivi:
- risanamento dell'economia (piano Dawes);
- dialogo con le potenze straniere (accordi di Locarno).

Gli Stati Uniti si rendono conto che la Germania non avrebbe mai potuto pagare le riparazioni e quindi
investono capitali in eccesso nell'economia tedesca.

La Germania viene riammessa al dialogo internazionale.

** Periodo di relativa stabilità
Non c'è stato un piano di ripartenza interno, tutto dipende dagli investimenti americani.
Dal 1925-1928 si ha un periodo di stabilità.

Nel 1925 viene eletto Inderburg come presidente della Repubblica.

Nel 1928 ci sono le elezioni politiche e si crea un governo di base socialdemocratica.

Nel 1929 crolla la borsa di Wall Street. Le banche prestavano praticamente a tasso zero. Chiunque
poteva richiedere un prestito. Il ceto medio Americano vedeva la possibilità di un guadagno facile
attraverso gli investimenti in borsa. Ciò che fa sì che la valutazione delle aziende aumentasse
molto, facendo staccare dal valore reale.

Le banche iniziano a chiedere gli interessi ma gli investitori non riuscivano a trovare acquirenti
per le loro azioni. La Germania crolla a sua volta e gli investimenti cessano.

** L'ascesa di Hitler
La popolazione si estremizza (sia a sinistra che a destra) e i borghesi temono una rivoluzione comunista.
Hitler ed il suo partito nel 1928 avevaono il 2% dei voti.
Dopo il crollo di Wall Street, i nazionalsocialisti salgono al 18%. Hitler afferma che la crisi
della Germania sia dovuta alle potenze vincitrici.
Successivamente prende il 37% diventando il partito più votato.

** Incendio del parlamento
Nel 1933 viene incendiato il parlamento e la colpa ricade sui comunisti. Ciò giustifica un periodo di violenze
contro i comunisti.

Nel marzo del 1933 Hitler prende il 44%. Riesce a formare un governo insieme all'estrema destra.
Successivamente instaura il partito unico.

Nell'agosto del 1934 muore Hindemburg. At Hitler viene assegnato l'incarico di formare un governo.
Al tempo era cancelliere, ma si fa dare anche l'incarico di presidente della Repubblica.

** Provvedimenti di Hitler
- Concordato tra la Germania Nazista e la Chiesa.
- Notte dei lunghi coltelli => Attraverso la gestapo vengono uccisi alcuni esponenti del partito Nazista.

** Persecuzione degli ebrei in quattro fasi
Hitler aveva in mente il miglioramento della razza, e per questo motivo voleva la sterilizzazione eugenetica
di tutte le persone che non fossero in linea con i tratti ariani, ovvero disabili, zingari, omosessuali,
malati di mente ed ovviamente ebrei.

*** Propaganda antiebraica
Gli ebrei vengono trattati in modo ostile e vengono distinti dalle altre persone grazie alla stella di David
che dovevano indossare.

*** Leggi di Norimberga
Con le leggi di Norimberga, nel 1935 gli ebrei perdono la cittadinanza ed altri diritti politici e civili.

*** La notte dei cristalli (9-10 Novembre 1938)
Le vetrine di alcuni negozi appartenenti ad ebrei vengono infrante, case e sinagoghe sono distrutte ed alcune
persone uccise.

*** Deportazione dei Lager e soluzione finale
Durante la seconda guerra mondiale.

** La politica economica di Hitler
L'obiettivo era quello del risollevamento dell'economia successiva alla crisi del 1929.

- Autosufficienza alimentare nel settore agricolo;
- Riarmo nel settore industriale.

Piena occupazione nel 1938.
