#+title: Prima guerra mondiale

* Cause dello scoppio della guerra

** Cause politiche:
- Germania voleva diventare prima potenza mondiale al posto dell'inghilterra;
- La Francia voleva prendersi la rivincita contro la Germania;
- Crisi dell'impero ottomano: gli altri stati volevano espandersi. La prima a farlo fu l'Austria;
- La presenza di due blocchi militari contrapposti: triplice alleanza (Germania, Austria, Italia) 
e triplice intesa (Gran Bretagna, Francia e Russia).

** Cause economiche:
- Rivalità tra le colonie da parte delle potenze industriali

** Cause militari:
- Corsa agli armamenti spinta dai gruppi industriali

** Cause culturali
- Nazionalismo: volontà di affermare la propria nazione sulle altre;
- Applicazione del Darwinismo: la guerra decide le nazioni che dominano;
- I giovani borghesi volevano affermarsi grazie alla guerra;
- Futurismo, la guerra era la sola igiene del mondo.

* Lo scoppio della guerra
Il 28 Giugno 1914 *l'arciduca Francesco Ferdinando*, erede al trono Austriaco, *viene assassinato* da un ragazzo Serbo.
*L'Austria chiede alla Serbia di consegnargli l'assassino*, tuttavia la Serbia è costretta a rifiutare poichè aveva
stretto un accordo con la Russia.

*Un mese dopo*, il 28 Luglio 1914, *inizia la guerra* tra *Austria e Germania* contro *Serbia, Russia, Francia ed Inghilterra*.
Inizialmente *si pensa ad una guerra lampo* per via delle nuove tecnologie, tuttavia così non fu e la guerra si
trasformò in una *guerra di logoramento*.

* Neutralisti vs Interventisti
L'Italia si divide in *due fazioni*: *neutralisti* ed *interventisti*.

** Non volevano entrare in guerra
Opinione pubblica, liberali (Giolitti), cattolici e la maggior parte dei socialisti non volevano entrare in guerra.
Giolitti non voleva che l'Italia entrasse in guerra perchè pensavano che non fossero pronti.

** Volevano entrare in guerra
Nazionalisti, irredentisti, gli industriali volevano entrare ed una parte dei socialisti nazionalisti.

* L'ingresso dell'Italia nella guerra