#+title: Rivoluzione Russa

* Prima della rivoluzione
Fino alla metà del 1900, insieme alla Russia c'erano diversi popoli (Russi, Finlandesi, Polacchi, ecc) e lo 
Zar aveva il potere assoluto. Era il paese più arretrato economicamente e oppresso politicamente in Europa.

* Partiti in opposizione allo Zar

- social rivoluzionario (populista)
- social democratico (marxista)

Il partito social rivoluzionario era contro l'industrializzazione, pensava che la
rivoluzione sarebbe dovuta partire dai contadini e voleva abbattere lo Stato per costruire
delle comunità agricole.

Il partito socialdemocratico, al contrario, era favorevole all'industrializzazione,
pensava che la rivoluzione dovesse partire dal proletariato e voleva abbattere lo
Stato per fondare una Repubblica Socialista.

* Le due correnti del partito socialdemocratico
- Bolscevichi: rivoluzionari
- Menscevichi: riformisti e moderati

I Bolscevichi, guidati da Lenin, volevano un potere centrale e il passaggio al comunismo.
I Menscevichi, guidati da Martov, al contrario, volevano riformare la società alleandosi
con la borghesia e istituendo una democrazia parlamentare.

* Rivoluzione del 1905
Dal 1904 al 1905 c'è una guerra tra Russia e Giappone. La Russia entra in una crisi,
i prezzi aumentano e le condizioni di vita peggiorano drasticamente.
Nel gennaio del 1905 140 mila persone sfilano a San Pietroburgo e raggiungono il palazzo
d'Inverno, residenza dello Zar. L'esercito apre quindi il fuoco sui manifestanti.
Nascono così i Soviet, scioperanti nelle fabbriche e nelle campagne. Per questo motivo,
lo Zar Nicola II è costretto a promettere maggiori libertà, anche se nella realtà non
avranno effetto.

* Chi sono i Soviet
Soviet in Russo significa "consiglio" ed erano i rappresentanti popolari eletti
nelle fabbriche e nelle campagne. Essi si ponevano come organo di governo, e tra
i più importanti c'era Trotsky, Soviet di San Pietroburgo.

* Rivoluzione del 1917
La situazione precipita con la prima guerra mondiale e sono costretti ad arruolare i
contadini, perdendo il lavoro. La crisi economica è ancora più grave, essendo la Russia
un paese agricolo.
A Febbraio del 1917 gli operai di Pietroburgo inducono uno sciopero generale
occupando le fabbriche. Richiedevano la redistribuzione della terra e l'instaurazione
di una democrazia.
Le truppe dello Zar si rifiutano di aprire il fuoco e si schiarano dalla parte dei civili.
Lo Zar, non essendo più in grado di gestire la situazione, abdica nel 2 Marzo 1917 e viene
proclamata la Repubblica.

* I centri di potere della Repubblica
- Potere legittimo (governo provvisorio) sostenuto prima dal principe L'vov e poi dal socialrivoluzionario Rerenskij
- Potere concreto (Soviet di Pietrogrado)

Entrambi i governi hanno intenzione di continuare la guerra, il governo provvisorio
poichè avrebbe rafforzato il potere ed i consensi e o soviet perchè volevano sconfiggere
le potenze imperialiste per la loro rivoluzione.
I problemi economici della Russia vengono rimandati alla fine del conflitto.

* Il ritorno di Lenin
Lenin era stato esiliato per aver fallito la rivoluzione nel 1905. Nel 1917 fa pressioni 
per tornare in Russia, con l'aiuto dei Tedeschi poichè il suo ritorno avrebbe gettato
la Russia nel caos.
Presenta le tesi di aprile secondo cui tutto il potere sarebbe dovuto essere nelle mani
dei Soviet:

- Tutto il potere ai Soviet
- La Russia esce dalla guerra
- Le terre vengono sequestrate e messe a disposizione dei contadini

Grazie a queste tesi, Lenin riceve il consenso delle masse.

* Rivoluzione di Ottobre
I consensi dei bolscevichi (rivoluzionari) aumentano. Il 25 Ottobre riescono
a conquistare il palazzo d'Inverno, sede del governo provvisorio. La rivoluzione
non è violenta e si contano poche vittime. Lenin a questo punto sale al potere.

* I provvedimenti

- Richiesta della resa della Russia per la prima guerra mondiale
- Abolizione della proprietà privata e confisca delle terre
- Nazionalizzazione delle industrie

* Perdita all'assemblea costituente
I bolscevichi ricevono una grossa perdita all'assemblea costituente, ricevendo
solo il 25\% dei voti, con la maggioranza ai rivoluzionari di Kerenskij con il
consenso dei contadini. A questo punto Lenin abbandona le elezioni ed instaura
una dittatura.

* Guerra civile del 1918-1920

- Armata bianca: minaccia interna, proprietari terrieri, sostenitori dello Zar e rivoluzionari sostenitori di Kerenskij
- Armata rossa: minaccia esterna, governi dell'Intesa che vogliono eliminare il governo per costituire una repubblica

Nel 1918 Lenin ordina l'uccisione dello Zar e della famiglia.
Nel 1920 finalmente la guerra si conclude e vince l'armata rossa sostenuta dalle
masse contadine.

* Politiche economiche di Lenin
Durante la guerra civile le condizioni economiche erano peggiorate ulteriormente. Inizia
il comunismo di guerra, lo Stato controlla tutti i settori dell'economia e nazionalizza
tutta la terra così come le grandi aziende. Nel 1921 la crisi si aggrava maggiormente
per via di una carestia che colpisce le campagne.

Per questo motivo, Lenin reintroduce la NEP (nuova politica economica), che prevede
la reintroduzione della piccola proprietà privata, sia per le fabbriche che per i campi.
Grazie a questa liberalizzazione, lo Stato riesce ad uscire dalla carestia.

* La nascita dell'URSS
La Russia diventa una repubblica federale a cui si legano tutte le altre repubbliche
socialiste. Nasce quindi l'Unione delle Repubbliche Socialiste Sovietiche.
Di fatto però, l'URSS è amministrata da un partito unico, ed è quindi una dittatura.
Le decisioni del partito non possono essere contrastate.

* La morte di Lenin
Lenin muore nel 1924 per problemi di salute. Alla sua morte, la scelta era tra Trotsky
(esercito) e Stalin (partito).
Stalin voleva il comunismo, Trotsky voleva la democrazia.
Stalin voleva proseguire con la NEP, Trotsky voleva abolirla ed accelerare il processo
di industrializzazione.
Stalin voleva rafforzare il socialismo in URSS, Trotsky voleva sostenere la rivoluzione
negli altri Paesi europei.
Alla fine vince Stalin, mentre Trotsky viene esiliato e muore nel 1940 grazie ad un 
sicario di Stalin.

* Gestione dell'URSS di Stalin
- Industrializzazione forzata con piani quinquennali
- Aumento di materie prime
- Contadini reclutati a forza dalle campagne come operai
- Collettivizzazione forzata dell'agricoltura
- Eliminazione forzata di ogni opposizione, con una condanna senza processo.
