#+title: Seconda Guerra Mondiale

* La vigilia della guerra

** Hitler annette la l'Austria e la Cecoslovacchia
Anche Mussolini segue la stessa scia ed annette l'Albania.
Francia e Inghilterra si dimostrano arrendevoli.

Hitler e Mussolini firmano il Patto d'acciaio -> l'Italia entra in guerra a prescindere,
anche se fosse la Gemania ad attaccare.

** Nel 1939 -> patto Ribbentrop-Molotov tra Germania e Russia
Hitler decide di firmare il pattro con Stalin in cui si giurava la non aggressione
con l'espansione della Germania. Inoltre si spartivano la Polonia, parte del patto
che rimane segreta.

** Invasione della Polonia nei primi di settembre
Quando invade la Polonia intervengono anche Francia ed Inghilterra dichiarando guerra
alla Germania.

Conquista anche la Danimarca e la Norvegia.

La prima guerra mondiale si era trasformata in guerra di logoramento. In questo caso, Hitler
riesce ad arrivare a Parigi nel giro di un mese.

La Francia si arrende.

La Francia si divide tra Nord e Sud. La parte Nord subisce l'occupazione tedesca, mentre
a Sud abbiamo la Repubblica di Vichy.

I soldati francesi collaborano con la Germania (forse).

Scappa dal porto di Danquerque per rifugiarsi in Inghilterra.

** Mussolini inizialmente non voleva entrare in guerra perchè l'Italia aveva subito grosse perdite sia nella guerra di Etiopia sia nella guerra civile spagnola.
La guerra sembrava lampo, perciò Mussolini entra in guerra all'ultimo per sedersi al tavolo dei
vincitori ed ottenere le terre. Entra il 10 Giugno e il 14 la Francia crolla.

L'Italia aveva pochi soldati.

** Due battaglie che la rendono una guerra di logoramento
Le due battaglie sono Operazione Barbarossa ed Operazione Leone Marino (con cui Hitler
decide di attaccare l'Inghilterra).

*** Leone marino
Il presidente Churchill aveva dichiarato di proseguire ad oltranza la guerra contro la Germania.
Si combatte tramite l'aviazione.

Nessuna delle due potenze prevale sull'altra -> guerra di logoramento

*** Barbarossa
La Germania attacca la Russia nonostante il patto di Ribbentrop-Molotov. Hitler voleva anche
il territorio dell'URSS. Considerava gli slavi come una popolazione inferiore.

** Il patto Tripartito
Dopo l'asse Roma-Berlino ed il patto di Acciaio, al patto Tripartito si aggiunge il Giappone.
Queste tre potenze pensavano di spartirsi il mondo.

** I Giapponesi attaccano la base navale a Pearl Harbour
Perchè non permettevano di vendere le armi.

Gli Stati Uniti entrano in guerra l'8 dicembre 1941 con il presidente Roosevelt (rieletto per la
terza volta).

** La svolta (dal 1942 al 1944) (nella slide non si capisce nulla)
Si ribaltano le sorti del conflitto.
Generale Rommel.

Vanno a combattere in Africa.

Ottobre-Novembre 1942 le sorti si ribaltano con tre battaglie tra cui lo sbarco in Normandia.

Luglio 1943 sbarco in Sicilia.

Il Re toglie i poteri a Mussolini e vuole togliere la dittatura. Viene imprigionato sul
Gran Sasso. Nel Luglio del 1943 si deve creare un governo 2

** 3 Settembre 1943 Bagoglio firma l'Armistizio con gli alleati
I soldati però non avevano ricevuto nessuna informazione.

Sempre a Settembre i Tedeschi scarcerano Mussolini che crea la Repubblica di Salò.
Il Re e Badoglio lasciano Roma per rifugiarsi a Brindisi perchè era già stata ritirata.

I soldati non sapevano ancora cosa fare.

** Nasce il comitato di liberazione nazionale
Punto di incontro: marzo 1944 con discorso Togliatti in cui dice che era necessario lavorare insieme
per cacciare i nazifascisti.

Il Re abdica per lasciare il trono al figlio.
