#+title: Seconda Guerra Mondiale

* La vigilia della guerra

** Hitler annette la l'Austria e la Cecoslovacchia
Anche Mussolini segue la stessa scia ed annette l'Albania.
Francia e Inghilterra si dimostrano arrendevoli.

Hitler e Mussolini firmano il Patto d'acciaio -> l'Italia entra in guerra a prescindere,
anche se fosse la Gemania ad attaccare.

** Nel 1939 -> patto Ribbentrop-Molotov tra Germania e Russia
Hitler decide di firmare il pattro con Stalin in cui si giurava la non aggressione
con l'espansione della Germania. Inoltre si spartivano la Polonia, parte del patto
che rimane segreta.

* Invasione della Polonia nei primi di settembre
La Guerra scoppia il 1 Settembre 1939 con l'invasione della Polonia da parte di Hitler.
Già da prima dello scoppio, la Germania, violando il trattato di Versailles, stava conquistando terre.

Quando invade la Polonia intervengono anche Francia e Gran Bretagna non possono più stare a guardare
e rispondono.

L'invasione della Polonia è molto rapida, la Germania infatti utilizza la startegia della guerra lampo
in modo da non dover sostenere una guerra lunga e logorante. 

Dopo la Polonia conquista anche la Danimarca e la Norvegia, i suoi attacchi infatti sono molto efficaci.

* L'Italia ritarda l'ingresso in guerra
Nonostante il patto d'acciaio stretto con Hitler, l'Italia decide di ritardare l'entrata poichè
non si sentiva ancora pronta militarmente.

* La sconfitta della Francia
Hitler attacca la Francia passando per i Paesi Bassi e per il Belgio (che si era dichiarato neutrale).
A Dunkirk ci fù una delle più grandi sconfitte delle truppe inglesi.

A Giugno del 1940 le truppe Tedesche arrivano a Parigi.

La Francia si divide tra Nord e Sud. La parte Nord subisce l'occupazione tedesca, mentre a Sud 
abbiamo la Repubblica di Vichy, un governo collaborazionista con gli invasori.

* L'Italia entra un guerra
La guerra sembrava lampo, perciò Mussolini entra in guerra all'ultimo per sedersi al tavolo dei
vincitori ed ottenere le terre.
Entra il 10 Giugno e subito dopo la Francia crolla.

L'Italia voleva partecipare alla guerra indipendentemente e quindi decide di attaccare la
Grecia. Riuscirà a conquistarla solo grazie all'intervento tedesco.

Anche in Africa prova a sottrarre l'Egitto dagli Inglesi. Nel 1941 l'Italia perde l'Etiopia
e la Germania interviene anche in Africa.

L'Italia quindi ottiene delle grosse sconfitte.

* Operazione contro la Gran Bretagna
La battaglia si svolge nei cieli. Hitler avrebbe dovuto distruggere l'aviazione militare
inglese. Grazie ai radar però gli inglesi potevano individuare gli aerei nemici
permettendo una delle prime grandi sconfitte della Germania.

* Germania ed Italia si alleano con il Giappone
Il Giappone aveva provato ad invadere la Cina e così si formò il cosiddetto "patto tripartito"
con le tre potenze.

* Operazione contro l'URSS
Hitler e Stalin avevano un patto di non aggressione conosciuto come patto Ribbentrop-Molotov, 
creato per evitare che l'Unione Sovietica rispondesse in seguito all'invasione della Polonia e 
per i sovietici per ottenere dei territori.

A Giugno del 1941 dopo aver conquistati gran parte dell'Europa, la Germania invade anche l'Unione
Sovietica, conosciuta come Operazione Barbarossa.

* Due battaglie che la rendono una guerra di logoramento
Le due battaglie sono Operazione Barbarossa ed Operazione Leone Marino (con cui Hitler
decide di attaccare l'Inghilterra).

** Leone marino (Germania vs Gran Bretagna)
Il presidente Churchill aveva dichiarato di proseguire ad oltranza la guerra contro la Germania.
Si combatte tramite l'aviazione.

Nessuna delle due potenze prevale sull'altra -> guerra di logoramento

** Barbarossa (Germania vs URSS)
La Germania attacca la Russia nonostante il patto di Ribbentrop-Molotov. Hitler voleva anche
il territorio dell'URSS. Considerava gli slavi come una popolazione inferiore.

L'URSS però riuscì a resistere, complice anche il duro inverno Russo.

* L'entrata in guerra degli Stati Uniti
Gli Stati Uniti entrano in guerra l'8 dicembre 1941 con il presidente Roosevelt (rieletto per la
terza volta) poichè i Giapponesi attaccarono la base navale a Pearl Harbour.
La guerra si sposta quindi nell'Oceano Pacifico.

* La svolta della guerra
Nel 1941 ci sono tantissimi fronti di guerra aperti. Dopo l'entrata degli Stati Uniti si ribaltano 
le sorti del conflitto. Le truppe di Hitler erano ferme in Russia dove riceveranno una grande
sconfitta.

Nel Maggio del 1943 l'Italia è costretta ad abbandonare l'Africa.

* La soluzione finale
Nel 1943 gli ebrei vengono internati nei campi di sterminio.

* Sbarco in Normandia

* Luglio 1943 sbarco in Sicilia
Gli Americani sbarcano in Sicilia con l'obiettivo di salire a Nord, costringendo le truppe di Hitler
a spostarsi dagli altri fronti. Questo momento portò al crollo del fascismo, facendo arrestare Mussolini
dal Re. Il partito fascista inoltre viene sciolto.

* 3 Settembre 1943 Bagoglio firma l'Armistizio segretamente con gli alleati
L'armistizio viene reso pubblico l'8 settembre ma i soldati però non avevano ricevuto nessuna informazione
e non avevano idea di cosa fare.

A Settembre i Tedeschi scarcerano Mussolini che crea la Repubblica di Salò.
Il Re e Badoglio lasciano Roma per rifugiarsi a Brindisi causando confusione ed incomprensioni.

* La resistenza
Alcuni gruppi di cittadini, chiamati Partigiani, sacrificarono la loro vita per combattere contro i tedeschi.

* Nasce il comitato di liberazione nazionale
Punto di incontro: marzo 1944 con discorso Togliatti in cui dice che era necessario lavorare insieme
per cacciare i nazifascisti.

Il Re abdica per lasciare il trono al figlio.
